### ISSUE TITLE
Add "CryptPad" to the login page title

### ISSUE THREAD

**Issue by davidbenque** [xwiki-labs/cryptpad#1043]
>Would you be so kind and add "cryptpad" to the title of the login web page? Right now, there is only "Login". This makes it hard for Keepass to recognize the page and find the corresponding entry.

on [Mastodon](https://social.tchncs.de/@Gianluca/110422476398098069)

While the point about Keepass is unrelated, it is strange to have only "Log in" as the page title. We could add "CryptPad" or the instance name.

**Comment by lemondevxyz** [comment]
I think either a new translation key needs to be added to Weblate because `login_login` is used across the application in ui elements (such as buttons) or one could combine `login_login` with a `instance_name` translation through Javascript.

I'd advise against the latter because in my language, Arabic, it would be grammatically incorrect.

> Hello! I tried to fix this issue, but so far it's working on my dev instance only hardcoded in the login.js file: modifying
> `              h('div.row.cp-page-title', h('h1', Msg.login_login)),`
> in
>  `             h('div.row.cp-page-title', h('h1', "CryptPad")),`
> I am aware this is not ok. I tried to add a new key in the messages.json file https://github.com/cryptpad/cryptpad/blob/main/www/common/translations/messages.json, but it didn't work.

The reason that didn't work because it changed the headline of the page, not the title. To change the title, go to `./customize.dist/pages/login.js:9` and change `Msg.login_login` to your desired value.

Lastly, I wanted to note that any files in CryptDrive already exhibit this strange behavior. If you open a file in Kanban, it doesn't say "Kanban - Your file name" it says "Your file name".
