### ISSUE TITLE
Anchors don't work anymore

### ISSUE THREAD

**Issue by ghost** [xwiki-labs/cryptpad#1226]
### Description

Since CryptPad 5.4.0 and the last CKEditor update, anchors don't work anymore on Rich Text.

See this example: https://cryptpad.fr/pad/#/2/pad/view/CgJix7P3FCdZJ5i0mvOKEasD8G24xGTup6hxWEeOhNA/

### Steps to reproduce

1. Create a Rich Text document
2. Add an anchor somewhere
3. Click the Go to anchor button
4. It doesn't work

### Expected behavior

Anchors should be working.

### What opreating system are you using?

Linux/BSD/UNIX, Apple macOS

### What browsers are you seeing the problem on?

Mozilla Firefox

### Extensions

uBlock Origin, Wappalyzer, Passbolt

### Version

5.4.1

**Comment by FWDekker** [comment]
I am experiencing the same issue on Linux, Debian Testing (Trixie). The issue occurs in both Firefox 117.0 and Chromium 116.0.5845.110, both using fresh profiles without any extensions or custom settings.

Important to note is that jumping to an anchor works in the document's preview. (Accessible from the "Tools" toolbar, the icon with the page with a looking glass. Clicking this button opens the page `https://sandbox.cryptpad.info/pad/inner.html?ver=5.4.1` and then (somehow) loads the original document.)

In the preview, clicking the text that links to the anchor jumps immediately to `https://sandbox.cryptpad.info/pad/inner.html?ver=5.4.1#name-of-the-tag` (where `name-of-the-tag` is, well, the name of the tag).

In the editor, clicking the text that links to the anchor shows a tooltip with a link "Go to anchor". This "Go to anchor" also links to `https://sandbox.cryptpad.info/pad/inner.html?ver=5.4.1#name-of-the-tag`, but that obviously doesn't work, because we're not in `https://sandbox.cryptpad.info/pad/inner.html?ver=5.4.1` but in `https://cryptpad.fr/pad/#/2/pad/edit/somehexadecimalid/`.
