### ISSUE TITLE
Old Datastore restored - Pads won't open

### ISSUE THREAD

**Issue by pojebunny** [xwiki-labs/cryptpad#179]
I've been using cryptpad hosted on my own machine for collaboration with friends till June this year.
Today I wanted to view my old pads so I've copied "datastore" from backup to the latest version of cryptpad.

Unfortunately I can't open any of the previously saved pads, though all the presentations and codepads open all right.
I'm currently trying to open these pads through CryptDrive (old accounts also work fine with the new version)

P.S.
Is there any way to remove the storage limit on self hosted cryptpad or is also a limitation for self hosting users?

**Comment by ansuz** [comment]
Hi.

Generally all we do is increment version by version (every two weeks). Occasionally we implement a migration of the encrypted documents which is run by clients. These migrations are tricky because we can't see the information we're supposed to migrate. It's possible you found some edge case where one of the migrations did not run successfully.

The easiest way to recover these documents would be to load them with an older version of CryptPad (ideally the same version which was used to author them). Assuming they load without issue, they could be exported and reimported into your new installation.

Updating every 2-3 versions keeps you closer in line with our deployment strategy. This is not required, but we're more likely to catch bugs which would affect our own instance.

**Comment by ansuz** [comment]
To answer your question about the storage limit, the value can be set within your configuration file.
