### ISSUE TITLE
Problem with the "drive", "todo", and tasks" pages

### ISSUE THREAD

**Issue by stoutouloutou** [xwiki-labs/cryptpad#194]
Hello,
Since I updated from version 1.16 to 1.19, some pages do not display properly : 

![screenshot](https://user-images.githubusercontent.com/4473579/32550949-2d20be84-c48f-11e7-80c7-65ad8b1e3be8.jpg)

the others (pad, code, poll, slide, whiteboard) work well...

Would any on help me sole this problem ?
I'm using docker, behind nginx.

Thanks !

**Comment by ansuz** [comment]
This could be caused by a customized stylesheet in the `cryptpad/customize/` directory (perhaps your version is missing a variable which is used in a newer version).

Otherwise, it could be a caching issue. Could you try opening it with several browsers (including incognito mode) and see if this behaviour goes away?j

**Comment by stoutouloutou** [comment]
Thanks for the advices !
I started the install from a fresh "git clone" instead of a "git pull", clear my browser cache, and it works.
As I didn't check between the 2 operations, I cannot know whether it was only the browser cache...
