### ISSUE TITLE
Remove inactive users

### ISSUE THREAD

**Issue by koulaxizis** [xwiki-labs/cryptpad#200]
First of all, congratulations for your work and thank you for releasing it as an open-source project!

I got a suggestion to make: I think it would be nice if there was an option for inactivity policy. If any registered users are inactive for a certain amount of time (six months, a year etc), they should be automatically removed.

**Comment by ansuz** [comment]
Thanks for your kind words!

Regarding your feature request:
CryptPad is something of a distributed application, with most of the logic implemented in the browser. Our server is implemented in javascript, but it could be any language, as long as it were able to offer websocket support to talk to clients.

Similarly, we've implemented storage using the native file system. If you're hosting your own CryptPad, you can look in your `datastore` and `pins` directories for all of your user data.

`datastore` contains all of your users' channels (the data type for pads, drive, and chat histories).

`pins` contains a history of channel usage per registered user. This history allows the server to determine how much storage space is being occupied by all the files in a user's drive.

By this methodology, it's possible to infer which channels can be deleted by crawling all of the pin files, and checking against which channels are absent from the constructed list. CryptDrives, and all associated user preferences would be included in this list (all user data except pins are encrypted/decrypted clientside).

The benefit of doing everything on the filesystem is that almost any programming language should be able to make a `stat` system call to see the last access time of the relevant files. Pin logs which have not been accessed in a given amount of time can be considered unused, and can be deleted. After that, channels which are unused and unpinned can be removed as well.

Because policies about this kind of thing may differ across organizations, we've left them out of the server code. I think the best way to implement something like this would be as external scripts run by the server operator on a set schedule, or whenever disk space gets low.

If you're interested in helping out with something like this, I'd be happy to help out, and I'm sure it would be greatly appreciated by the other operators who are also hosting CryptPad instances.

**Comment by pintman** [comment]
It would be could to have this information somewhere documented.

**Comment by ansuz** [comment]
We implemented the optional removal of inactive accounts some time ago. It's mentioned in [config.example.js](https://github.com/xwiki-labs/cryptpad/blob/main/config/config.example.js#L203-L211) above the `accountRetentionTime` config option.
