### ISSUE TITLE
drive doesnt get loaded

### ISSUE THREAD

**Issue by petrk94** [xwiki-labs/cryptpad#219]
Hello,

I have installed and can run successful server.js with /package/host/localhost/nodejs-6.9.1/bin/node server.js.
The problem is, on the home page I see everything, but the signup process is slow and the forward to xxx.tld:3000/drive
 
![unbenannt](https://user-images.githubusercontent.com/19719052/34921569-b02efe06-f984-11e7-92f6-05151b19c339.PNG)

![unbenannt](https://user-images.githubusercontent.com/19719052/34921604-29b44fd8-f985-11e7-9b0b-aa57ae0fde75.PNG)

I can call it only over http://cryptpad.xxx.tld:3000
By trying to open over https, I get the error message that the connection got closed.
Can you help?

Thanks

**Comment by frju365** [comment]
First, I suggest you to make a correction to your CSP nginx/apache2 header. Because they are blocking the scripts and fonts.
On nginx, your conf could be this : 
``` 
add_header Content-Security-Policy "script-src 'self' ; ";
```
instead of "self", write in your conf : "domain.tld" because in fact you configure the conf for localhost and not for your domain, so it is blocking the script from your domain.

And I don't have the complete CSP log errors, but you can allow the google font by adding in your CSP conf after the previous one between the " " : 
```
font-src: https://fonts.gstatic.com
```
this is a bit complicated. So, what server software have you got ? Nginx ? Apache ?

**Comment by petrk94** [comment]
@frju365 
I have contacted my hoster and they said that I need to change it in the config.js.
So how I do it?
Thanks

**Comment by petrk94** [comment]
@frju365 
The Hoster is using Apache Server.
So What I need to do?

**Comment by ansuz** [comment]
It would help if you could provide a copy of your current config.js and Apache server.

> the signup process is slow

The signup process is designed to be slow, since it uses the _scrypt_ password based key derivation function. The slowness is what makes it difficult for attackers to generate usernames and passwords by brute-force.

> I can call it only over http://cryptpad.xxx.tld:3000

Content Security Policy headers (CSP) enforce being able to load CryptPad only over one domain because it makes it impossible to execute a cross-site scripting (XSS) attack. This is a safety net in case there are vulnerabilities in the client-side javascript that would otherwise allow an attacker to access your list of pads and their encryption keys.

CSP headers are set by whatever is actually serving your content (Apache, or the node process, depending on your configuration). The warning you're seeing is because one of these things is telling your browser to only accept content from `localhost:3000`, and you are trying to load it from `cryptpad.digitaler-harz.de`.

Unless I'm mistaken, you must have customized your installation to use fonts from google, instead of self-hosting them as we do. If that is the case, you'll need to add a rule in your CSP settings which permits that domain.

If you've made other changes to your installation, it may also be helpful to know what they are.
