### ISSUE TITLE
Stacked on home page

### ISSUE THREAD

**Issue by Ecozzo** [xwiki-labs/cryptpad#236]
I've just installed cryptpad on my server. I can see the home page, but nothing else, loading other pages I have white screen and if I open the console of the browser I can see

Content Security Policy: The page’s settings blocked the loading of a resource at http://XXX:3000/common/loading.js?ver=1.29.0 (“script-src”).
Error: Script error for "/common/loading.js"
http://requirejs.org/docs/errors.html#scripterror

**Comment by ansuz** [comment]
This looks like a configuration problem. Content Security Policy (CSP) settings prevent malicious actors from injecting inline js, or loading js from other domains. It seems to be complaining because the settings from your configuration file forbid loading it on whatever domain you're trying to load it from.

You can check that your config matches the domain you're using in the browser (including the protocol (https or http)). Remember to restart the server after altering the config file.

**Comment by Ecozzo** [comment]
I'm using the config.example.js with http://XXX:3000 instead of http://localhost:3000/

**Comment by ansuz** [comment]
It could be a few different things:

1. you've configured it for http and you are accessing it over https
2. the default configuration file includes a leading space where `domain` is declared, and you may have removed it
3. you've done everything correctly, but you visited the site before changing the CSP config, and now the CSP headers are being cached

If the problem is option 1, make sure you're accessing it the exact address that the CSP headers are configured to allow. If the problem is option 2, you should re-add the leading space, and restart the server. Otherwise, try opening your site in a private window, so as to avoid caching problems.

Finally, if you visit [our chat channel](https://riot.im/app/#/room/#cryptpad:matrix.org), more people may be able to help you debug.

**Comment by Ecozzo** [comment]
Ok, it was option 3.
Thanks
