### ISSUE TITLE
Update German translation

### ISSUE THREAD

**Issue by polx** [xwiki-labs/cryptpad#239]
The German translation, [`customize.dist/translations/messages.de.js`](https://github.com/xwiki-labs/cryptpad/tree/master/customize.dist/translations/messages.de.js), should be updated to the latest development stage.

**Comment by polx** [comment]
Branch [de-translation-pl](https://github.com/xwiki-labs/cryptpad/tree/de-translation-pl) created.
Further work is expected:
* Reactualize after the two weeks dev
* Own proofreading
* Request for comments and discussion points (e.g. for decisions on the translations of zero knowlede, the dudzen, or...)

**Comment by ansuz** [comment]
Generally we don't try to translate _Zero Knowledge_. I'm not sure what you mean by _the dudzen_.

It looks like you've updated `reconnecting` from _Connection is being rebuilt ..._ to _Connection is established_. We use that one to indicate that we're in the process of connecting to the server, not that we have reconnected. That was found by chance using a translator and a random selection of existing keys which had changed.

My knowledge of Deutsch is inadequate to review any more.

@MacLemon, @michaelachmann: I believe you are both native speakers, if you have time, would you mind reviewing this update?

**Comment by michaelachmann** [comment]
Infact I had to google "dudzen" just to realize that it is a German term. The German language distinguishes between a formal and informal "you". ATM the translation is using the informal "du", @polx changed it to the formal "Sie", "dudzen" describes the habit of using the informal you. 

`reconnecting` in the new version is translated as "Connection is being established" ("Verbindung wird aufgebaut"), which transfers probably all necessary information.

**Comment by michaelachmann** [comment]
P.S. I've had a first look through the translation: Before commenting more I'd say we should decide for the formal or informal form and afterwards update the translation accordingly. In de-translation-pl the forms are yet mixed.

**Comment by ansuz** [comment]
In the French translation we generally use the formal you (_vous_), but I think this is less a matter of our policy and more a matter of what's common in the German language in recent years.

Personally I'd pick some piece of software that uses comparable semantics and adopt the tone they use, as we want users to encounter prompts with which they are already familiar.

**Comment by kpcyrd** [comment]
As a native speaker:

- I would recommend keeping "Zero Knowledge" as-is, adopting technical terms from English into German is very common.
- "Connection is being established" ("Verbindung wird aufgebaut") would translate to `connecting`, while `reconnecting` implies that the connection has been lost, not sure if this is important though.
- I think the informal "you" is perfectly fine and very common, especial among "personal use" applications. The formal "you" often feels foreign and I'm not sure when I last used an application that did this.

**Comment by polx** [comment]
As the **informal** form was there before, I tried to respect things and it has given me a hard time. I think German folks are bit more keen at the informal wording than the French folks but even there, I don't find it very usual but I know some platforms use it (e.g. the ikea website or wikipedia); however I use an amount of applications which use the formal form (e.g. MS Word or Internet Explorer; I guess I notice these more easily as a non-native). I see however, that I was not careful to keep it consistent and need to homogenize things. 

Similarly, zero-knowledge was translated befreo to "ohne Preisangabe von Informationen" (in the commit 6dacbf2bd98be9c5343ab042f28b9f727fce7ccc).  This does not necessarily come very natural,  especialy when you have slogan-like statements. I see that this got changed a few times (an earlier version was "ohne Vorwissen" which would be a literal translation of "zero knowledge"). "ohne Preisangabe von Informationen" carries the intention rather well ("we don't give a price to your information"). I have tried to respect this "ohne Preisangabe von Information" as it seems to be carrying the intention and is an honourable attempt at rejecting foreign slogans which often are misunderstood. This is so bad in Germany that we had a big poster-campaign indicating "Don't be a maybe", a sentence that no native English speaker I asked could ever make sense with. I am happy if we find yet a better attempt.

In the "reconnecting" message, it has not appeared to me very useful to extend the sentence from "Verbindung wird aufgebaut" to "Verbindung wird neu aufgebaut" to indicate the "again" aspect of reconnecting. @ansuz, is it important to differentiate the first connection and the subsequent connections?

**Comment by polx** [comment]
@michaelachmann  and @kpcyrd , can you confirm that most of the apps you use indeed are using the informal form? I find it is rather important to appear a bit professional even if the fist was a slogan for a while for CryptPad. I see Google Docs and Drupal are using the formal form but Stackfield, Wordpress, Jimdo and Joomla are using the informal form.

Als, @michaelachmann  and @kpcyrd, do you have a better suggestion for "zero knowledge" or a stronger feeling to keep "zero knowledge" ? I'd prefer to keep it up with "ohne Preisangabe ihrer Informationen".

@ansuz , anything serious behind "connecting again" vs "connecting" ?

thanks in advance.

Paul

Paul

**Comment by ansuz** [comment]
@polx In your example regarding formal or informal, it looks like informal is winning. @michaelachmann wrote the previous translation with formal, and no one had any complaints about it, and @kpcyrd has said informal is very common. I would go with that.

I think all the other translations borrow the _Zero Knowledge_ phrase, but if German more commonly translates phrases like that, I'd keep with that habit, especially since it is already translated.

For _reconnecting_, I'm surprised German doesn't have a word which distinguishes between connecting and connecting a second time. Once again, if there are comparable services that have to connect/reconnect, their translation is probably acceptable for our purposes.

**Comment by michaelachmann** [comment]
@ansuz I used the informal version. 

For _Zero Knowledge_:  I guess I should have kept the English version in the first translation. The changes in 6dacbf2bd98be9c5343ab042f28b9f727fce7ccc turned my bad translation into quite a nice German slogan - I'd almost rather keep the new phrase. Nevertheless: Germans are used to English terms being mixed into their language. That'd be an argument for keeping the original term.

For _reconnecting_: It is possible to differentiate between connecting and reconnecting. Probably we should just change that string to a proper representation.

**Comment by polx** [comment]
@michaelachmann , I confirm you've pushed the informal usage and I'll make this complete soon.

For "ohne Preisangabe ihrer Informationen", I would like to attempt it. I find the zero-knowledge slogan to be somewhat geek oriented whereas "without making money from your information" is much more accessible to the normal mortal. I suggest that I try it.

For reconnecting, I haven't found a common translation. "Verbindung wird hergestellt" is a very very common usage, even if it appears wild and complex for non-natives (people might be interpreting a sense of a factory at work, no-one feels that). There is no such common usage for "rebuilding connection". "Neuverbindung im Verlauf" would be correct but pretty unnatural. @michaelachmann , do you have a common translation to suggest?

**Comment by ansuz** [comment]
Sorry @michaelachmann I meant to say informal. That's a typo.

**Comment by ansuz** [comment]
Regarding: _without making money from your information_ is not what we mean to say, because whether or not we make money from it does not communicate that we cannot read it. That's the important part to convey.

**Comment by polx** [comment]
"Preisgabe" (sorry that I wrote "Preisangabe" earlier) does not mean "we make money" but "we consider it to have a price", it could also be used to qualify a damage (and this case, the price would be something to pay). So I understand it as "we consider it to have a price we can leverage".

**Comment by polx** [comment]
More precisely: "Preisgabe" could be compared to the "reward" posters of the early far-west cow-boys where some gangsters where searched for and a reward was given to catch them.

**Comment by polx** [comment]
I have now, in 662f69eb0ca443dd0d3c746701591fb427a78f60, mainstreamed the usage of the informal tone. I would be happy if someone would give it a bit of a deeper review and/or we discuss more the two open issues left ("Ohne Preisgabe von Informationen" for "Zero knowledge" and a somewhat natural translation of "reconnecting").
paul

**Comment by ansuz** [comment]
We're planning to merge this branch today. Any updates are still welcome, but what we have is certainly an improvement.

**Comment by ilu33** [comment]
I wouldn't translate Zero Knowledge everywhere. It's a good slogan and can be remembered easily by germans. I vote for using both and changed the translation accordingly. 

"ohne Preisgabe von Informationen" sounds strange, I can't really say why. I'd prefer "ohne Preisgabe von Daten" because "Daten" is the word used in "Datenschutz". 
Just fyi: "Preisgabe" has nothing to do with prices. It means disclosure or abandonment.

I had a look through the german translation an noticed several mistakes:
1. Adressing somebody - formal or informal - needs capitalization: Du Dein Dir
I hope I caught all occurrences.
(deleted the rest)

Sod this, I'm forking. Too many corrections,  this is getting out of hand. Actually, this was much more work than I imagined beforehand. A lot of hours more. 

**If you want to attract more translators or even keep them (me!) you really have to look for a way to make things easier for non-coders (transifex link? weblate link?). Githubs GUI gave me lots of troubles and I'm not fit in using command line git.** 

These lines leave room for thought/debate:

    out.errorCopy = ' Du kannst noch den Inhalt woanders hin kopieren, nachdem du <em>Esc</em> gedrückt hast.<br>Wenn du die Seite verlässt, verschwindet der Inhalt für immer!';
-> Copying is still possible after pressing ESC, right?

    out.realtime_unrecoverableError = "Es ist ein nicht reparierbarer Fehler aufgetreten.. Klicke auf OK, um neuzuladen.";
-> The user doesn't know what a realtime engine is and doesn't care.

    out.useTemplate = "Mit einer Vorlage starten?"; //Would you like to "You have available templates for this type of pad. Do you want to use one?";
-> ???

    out.previewButtonTitle = "Die Markdownvorschau (un)sichtbar machen";
-> This sentence doesn't work in German. What is this exactly? 
Maybe: Die Layoutvorschau (un)sichtbar machen

    out.poll_bookmark_col = 'Setze ein Lesezeichen auf dieser Spalte, damit sie immer gleich editierbar angezeigt wird.';
-> Not sure about this one, but the original translation made no sense.

    out.fo_moveFolderToChildError = "Du kannst einen Ordner nicht in einen seiner Nachfolger verschieben";
-> Not sure about this one, but the original translation made no sense.

out.settings_pinningNotAvailable = "Gepinnte Dokumente sind nur für angemeldete Benutzer verfügbar.";
-> What's a good german word for "pinned documents" - the old translation "genagelt" is funny :-)

    //about.html lines 644-647
   out.main_about_p2
   out.main_howitworks_p1
-> These lines have no or different counterpart in the english messages.js.
Since the present messages.js made more sense I translated those and commented the old ones.

    // contact.html
    out.main_about_p2
-> Has no equivalent in the english messages.js.

    out.main_howitworks
    out.main_zeroKnowledge
    out.main_zeroKnowledge_p
-> ​Have no equivalent in the english messages.js, which is a shame because I especially liked the text in out.main_zeroKnowledge_p 

"Because sensitive assets can only be decrypted using employee access credentials, CryptPad removes the hacker jackpot which exists in traditional IT servers."
-> I'm having trouble to correctly interpret this marketing speak. The existing translation doesn't make any sense.

            "When you register, you generate a public key which is used to tell the server that the pads in your CryptDrive should not be deleted even if they are not actively being used." +
            " This information does reveal more about how you are using CryptPad, but the system allows us to remove pads from the server once nobody cares enough to keep them."
-> I don't understand this. Are owned pads kept or not? The original (machine?) translator obviously also did understand nothing.

While translating the FAQ I noticed that it adresses pretty advanced stuff. Average users wont understand most of it. That's not what a FAQ is for, IMHO.

**Comment by ilu33** [comment]
https://www.duden.de/sprachwissen/sprachratgeber/Gross-oder-Kleinschreibung-von-duDu-und-ihrIhr: "In all diesen Fällen empfehlen wir übrigens die Großschreibung." 
I see the capitalized "Du" as a middle way in between being too formal ("Sie") and too informal ("du"). If there's no input from other people the developer needs to just decide.

No 7, 11 and 12 still need an understandable translation. No 7 needs a good word for "pinned" and 11 and 12 need clarification in the original english text.

**Comment by polx** [comment]
Hello @ilu33,

>> 1. `out.errorCopy = ' Du kannst noch den Inhalt woanders hin kopieren, nachdem du Esc gedrückt hast. Wenn du die Seite verlässt, verschwindet der Inhalt für immer!';`
>> Copying is still possible after pressing ESC, right?

That sounds right to me: if you copy, you explode the space, if you don't, because you press escape, you can still open. 


2. `out.realtime_unrecoverableError = "Es ist ein nicht reparierbarer Fehler aufgetreten.. Klicke auf OK, um neuzuladen.";`
>>  The user doesn't know what a realtime engine is and doesn't care.

I tend to agree.  @ansuz maybe you can answer that? The realtime engine talked about here is the engine that allows the collaboration between several parties (realtime collaboration). Maybe replace by "Collaboration engine"?


3. `out.useTemplate = "Mit einer Vorlage starten?"; //Would you like to "You have available templates for this type of pad. Do you want to use one?";`

The message does not change whether or not a template is available. So... it can only be generic.

4. `out.previewButtonTitle = "Die Markdownvorschau (un)sichtbar machen";`
>> This sentence doesn't work in German. What is this exactly?
>> Maybe: Die Layoutvorschau (un)sichtbar machen.

Layoutvorschau does not appear correct to me either. "Vorchau" would be ok maybe. Markdownvorschau tries hint the rendering of the Markdownsyntax. I'm fine to reduce it to "Vorschau"


5. `out.poll_bookmark_col = 'Setze ein Lesezeichen auf dieser Spalte, damit sie immer gleich editierbar angezeigt wird.';`
>>  Not sure about this one, but the original translation made no sense.

Well, yours seems better (always displayed left vs always direct editable)

6. `out.fo_moveFolderToChildError = "Du kannst einen Ordner nicht in einen seiner Nachfolger verschieben";`
>> Not sure about this one, but the original translation made no sense.

Case corrections. Thanks.

7. `out.settings_pinningNotAvailable = "Gepinnte Dokumente sind nur für angemeldete Benutzer verfügbar.";`
>> What's a good german word for "pinned documents" - the old translation "genagelt" is funny :-)

Anheften would be the translation of "pin" of the Pinterest entry of de.wikipedia. I asked my 14 y son and he told "Klar pinne ich, aber nur wenn ich chaka spiele.". So it looks like this is yet another anglicism. Is _anheften_ ok? Then let's take it. Otherwise yours with "pinnen" is fine to me.

8. `//about.html lines 644-647`
>>` out.main_about_p2`
>>` out.main_howitworks_p1`
>> These lines have no or different counterpart in the english messages.js.
>> Since the present messages.js made more sense I translated those and commented the old ones.

I guess that this is just a matter of actualizing (this issue already has a few months).

9. >> `// contact.html`
>> `out.main_about_p2`
>> Has no equivalent in the english messages.js. Delete?

Yes, same comment.

10. `out.main_howitworks`
>> `out.main_zeroKnowledge`
>> `out.main_zeroKnowledge_p`
​>> Have no equivalent in the english messages.js, which is a shame because I especially liked the text in out.main_zeroKnowledge_p

The versioning system has it. I think it is fine to delete them.

11. `"Because sensitive assets can only be decrypted using employee access credentials, CryptPad removes the hacker jackpot which exists in traditional IT servers."`
>> I'm having trouble to correctly interpret this marketing speak. The existing translation doesn't make any sense.

Mmmh, what it says seems a bit clearer to me: Using the crypto-powered protection that cryptpad offers allows a company to keep things as private or shared as they want, by using their own internal logic without having to rely on otherwise attackable cloud services. Is that better understandable?


12. `"When you register, you generate a public key which is used to tell the server that the pads in your CryptDrive should not be deleted even if they are not actively being used." +`
`" This information does reveal more about how you are using CryptPad, but the system allows us to remove pads from the server once nobody cares enough to keep them."`

>> I don't understand this. Are owned pads kept or not? The original (machine?) translator obviously also did understand nothing.

No machine translation, there's at least a grammatical error ;-) (_du erstellst_ vs _erstellst du_).
I suppose this proposition bothers you: "Diese Information zeigt mehr zum Server, über wie du CryptPad benutzt,": It says, more or less, that the server knows more by "owning pads" (@ansuz and @cjdelisle , what more?) but that doing that prevents the old unvisited pads to be deleted in the regular housekeeping routines. Do you want to propose a better translation?

**Comment by ilu33** [comment]
11. I've had trouble with the hacker jackpot ... = Hauptgewinn? And I wouldn't identify "traditional IT servers" with cloud services ... traditional would mean on premises to me, as opposed to clouds. But your explanation sounds logical, so if that's what was meant, I can translate it. 

I'M not good at company marketing lingo. Maybe thats all good. But while reading those strings (and especially the FAQ) I got the impression that they had the nerd in mind while writing it, more than the average user. Maybe food for thought.

12. My problem here is not where you thought it is. It's the discrepancy in between the first sentence (even not used documents are kept) and the second sentence, second half  ("the system allows us to remove pads from the server once nobody cares enough to keep them.") -  this confuses me as a user: Are owned inactive pads kept or not? First sentence says yes, second says no.

**Comment by ansuz** [comment]
This has been a lot of feedback to review! Again, as a non-speaker, it's hard to make final decisions about someone else's language. English is a typically informal language, so that feels natural for me.

It also seems there's a disagreement between demographics. Personally, I tend to interpret interface text as coming from the app itself, and not from the organization that creates or hosts the app (though I know that it was written by a human). For people who have spent the majority of their lives editing via digital interfaces, it's pretty natural to personify applications as familiar entities. I figure this is probably what's behind the shift towards informal tones on the web, whether or not it's traditionally considered correct.

---

Now, regarding specific feedback:

1\.  This message in displayed in an error screen. It should explain that if you want to copy the content of the pad, you have to press "Esc" to close the error screen. You can't copy the content if you don't press "Esc" to close the error screen.

2\. We've discussed the usage of the term _realtime engine_, and we agree that it's unnecessarily technical. We plan to change it to _"An unrecoverable error has occured. Click OK to reload."_

3\.  This message is only displayed when templates are available. We use "Start with a template?" in the English version to keep it short.

4\. to 7\. I can't really comment here

8\. to 10\. These keys no longer exist in the (canonical) English version, so they're safe to delete

11\.   Hacker jackpot can be interpreted as _High value target_. This is very informal slang, and we should probably update the english version. I agree with _Traditional IT servers_ being less clear than _cloud services_, except that we are also a cloud service, albeit with a different set of properties/behaviours. _Traditional/non-encrypted cloud services_ might be appropriate. We'll see about updating the English version, making it more clear while keeping the same intended meaning

12\. By saying _once nobody cares enough to keep them_, we meant when they are no longer pinned by a user (meaning they're not stored in any registered user's drive). _Owned, inactive pads_ are always preserved by the server. Pads which are not in a registered user's drive will be removed by the server after the set period of inactivity (6 months of no changes to the file, in our case).

**Comment by ilu33** [comment]
No 12 needs an update in the english version - I would never have guessed that distinction. 
Since the FAQ question is about what  the server knows if I register I would avoid mentioning anything about the fate of abandoned documents here. Actually, "abandoned" is a good term.

My proposal:
1.
"This information does indeed reveal more about how you are using CryptPad. It's a compromise necessary to identify abandoned documents, since nobody could afford a system which keeps every single document forever."

2.        out.faq.keywords.abandoned: {
            q: "What is an abandoned Pad?",
            a: "An <em>abandoned pad</em> is a pad that is not pinned in any registered user's CryptDrive and that hasn't been changed for six month. Abandoned documents will be automatically removed from the server." 
        },

While I'm at it - shouldn't "pad" be replaced with "document" - since cryptpad is having not only pads, but also polls and kanban (except where it really means "pad")?

**Comment by ansuz** [comment]
It's already pretty hard to keep track of all the issues raised in this thread. For the sake of keeping things simple, I'd prefer to focus on issues with the Deutsch translation here.

We've made a note of your feedback and we'll take it into account for our updated version of the English translation.

**Comment by polx** [comment]
@ilu33 , @kpcyrd , @michaelachmann : I have started an issue dedicated to the personal address in German. I think we should harvest friends, families, and colleagues to express their opinion on this and collect comparables and references.
paul

**Comment by polx** [comment]
I believe that all issues raised in this thread are either:
* forked into another issue (e.g. [issue 235 on the personal address du/Du/Sie](https://github.com/xwiki-labs/cryptpad/issues/255)
* or resolved
I thus suggest to close this issue.
paul

**Comment by ansuz** [comment]
thanks!

**Comment by polx** [comment]
Seems like a week passed and we have indeed solved the issues mentionned here.
Thanks much to the contributors (@ilu33, @ansuz, @kpcyrd, and @michaelachmann). I hereby close this issue.
