### ISSUE TITLE
CryptPad Rich Document randomly deletes text 

### ISSUE THREAD

**Issue by lynxm** [xwiki-labs/cryptpad#241]
One of the departments in my organization has been using cryptpad for their collaborative documentation needs. 
When we are taking notes during a meeting, one person will type but no one else viewing the doc can see what they’ve typed. Additionally, text will randomly delete and when we click history it won’t update it just says “saved”. We use Firefox and Tor for this as well.
Any clarity y’all can give on this  @issue?``

**Comment by ansuz** [comment]
This sounds a lot like a subtle bug that was introduced in our API server in _v1.25.0_, which we believe to have fixed in _v1.29.0_.

The bug affected our checkpoint mechanism, which allows editors to edit the document without knowing its complete history. An incomplete heuristic allowed for editors to join under certain circumstances, and receive an insufficient amount of history for their patches to affect the document. Unfortunately, in these cases the other editors would ignore that person's invalid patches, and the person creating those patches views would view the other group as invalid as well. In blockchain terms, this is called a fork.

Since we believe that this bug has been fixed, it would be helpful to know when this happened last, and whether it was on a self-hosted CryptPad instance, or on our flagship server: https://CryptPad.fr, which is running the latest version.

If CryptPad.fr is still affected, then it would be very helpful if you could share such a pad's URL with us, so that we could try to diagnose whether it's a new case of the same bug, or a different cause.

If you're using a third-party server which was running a version between v1.25.0 and v1.29.0 when you last experienced this bug, it's possible that an upgrade to that instance's API server would mitigate this issue in the past.

If you need to share any sensitive information with us to diagnose this issue, feel free to contact us at support@cryptpad.fr, rather than listing it here on GitHub.

**Comment by lynxm** [comment]
I can’t share the pad URL on here so i sent an email. But we have been using CryptPad.fr

**Comment by ansuz** [comment]
We debugged the issue using the log of the channel you provided by email. Our fix to the bug I described had several components, one in our server, one in a module, and another in a branch in the CryptPad repository. 

Unfortunately, we failed to merge that branch to master for the last release. The CryptDrive app had the working fix, due to a slightly different architecture, but the collaborative apps like _/pad/_, _/code/_, etc. did not. Fortunately, this meant that all we had to do was merge that branch to master and deploy, so now the fix is both on our master branch, and live on CryptPad.fr. 

If you let your colleagues know to reload any collaborative sessions they have open, then their editors should start behaving as expected.

I'm sorry you were affected by our slip-up, and grateful for your help figuring out the issue.
