### ISSUE TITLE
Kanban feature wishlist

### ISSUE THREAD

**Issue by ilu33** [xwiki-labs/cryptpad#254]
- Export into xml/json
- 3 Item properties: Title, assignee and a per default hidden field for details/remarks/links
- background colors for items, color picker with #000000 color codes
- more colors for boards, color picker with #000000 color codes
- more space on the board - too much wasted whitespace at the moment 
- (option for a) condensed layout
- move the + sign into the toolbar
- resizable font size or at least much smaller defaults

**Comment by gitjeff2** [comment]
> Export into xml/json

This appears to be supported already. If you open a Kanban file, click the **...** area and select *Export* you'll end up saving the Kanban list to your local machine as raw JSON. 

Honestly, I think refactoring this so that Kanban files are stored as [YAML](https://en.wikipedia.org/wiki/YAML) would be better. YAML is more human readable in its raw form and it can be easily serialized into JSON if needed.

**Comment by ilu33** [comment]
Yes, the export feature seems to be done already. YAML would be nice but something is better than nothing.
A friend of mine is working on the other features, the colorpicker is already done. So I'm hoping for a PR soonish.

**Comment by ilu33** [comment]
Thank you @MTRNord !
