### ISSUE TITLE
Personal address in German (du, Du, oder Sie)

### ISSUE THREAD

**Issue by polx** [xwiki-labs/cryptpad#255]
The current translation of CryptPad in German speaks to you with the "du" pronoun...

That is the "familiar" way to speak to someone.

A proposal has been made to move to use the old-style "Du" as [pull-request](https://github.com/xwiki-labs/cryptpad/pull/253), which is felt by some to be more respectful.

We should collect evidences and feelings about this way of addressing:
 * Please indicate as a comment of this issue which variant you are advocating and whether you are a native German speaker.
* Please provide citations to to articles that explain why, how, and in which circumstances a given address should be used.

**Comment by polx** [comment]
As discussed on [issue 239](https://github.com/xwiki-labs/cryptpad/issues/239): Duden advises:
* [du should rather be written Du](https://www.duden.de/sprachwissen/sprachratgeber/Gross-oder-Kleinschreibung-von-duDu-und-ihrIhr)
* [Sie is written with a capital](https://www.duden.de/sprachwissen/sprachratgeber/Gross-oder-Kleinschreibung-von-sieSie)

**Comment by polx** [comment]
Personal opinion of mine (non-native German speaker in Germany since 18 years): Employ "Sie".

I'll note that:
* [Facebook](https://de-de.facebook.com/), [AirBnB](https://www.airbnb.de/), and [Ikea](https://www.ikea.com/de/de/) use "du".
* Most MicroSoft products, Apple products, [Xing](https://xing.com), [Spiegel](https://www.spiegel.de/meinspiegel/login.html), [Heise](https://www.heise.de/sso/login/), [Google Drive](https://www.google.com/intl/de/drive/) use "Sie". 
* I have not met yet one that says "Du" (that was only in personal communication).

My best way to inspect that is to go to the login-page of these sites.

**Comment by polx** [comment]
[This comment of @ilu33](https://github.com/xwiki-labs/cryptpad/issues/239#issuecomment-404256887) is certainly relevant. Copied here:

> https://www.duden.de/sprachwissen/sprachratgeber/Gross-oder-Kleinschreibung-von-duDu-und-ihrIhr: "In all diesen Fällen empfehlen wir übrigens die Großschreibung." I see the capitalized "Du" as a middle way in between being too formal ("Sie") and too informal ("du"). If there's no input from other people the developer needs to just decide.

While I understand the desire to appear more respectful compared to Facebook or Ikea (!), I do not feel that appearing more personal as in a letter is correct for a software. "all diesen Fällen" is precisely those cases of a personal address from a person to a person as far as I can read the Duden advise.

paul

**Comment by ilu33** [comment]
Ikea always (since the 70s) used the "du" to appear more swedish - as opposed to german. It gave them a foreign touch.

Those american companies (and advertising in general) use the "du" in a certain aggressive way, to intrude into the personal space of the user, to insinuate friendship which is obviously a lie. We all know how disrespectful those companies really are.

On a personal note: I would skip the capital D only with persons, I'm very very close to - if I'm in a hurry or on the smartphone. Or with people I don't respect. Even if most of the IT-crowd is not using "Sie" anymore, I would never be as disrespectful as skipping the capital D. 

You never make a mistake by picking "Sie" like the other mentioned companies. "Du" is ok if you want to be more informal. I think "du" is a no-go.

Disclaimer: I'm not in my twenties anymore. Young people might not care about spelling or grammar or whatever.

This has been open for discussion long enough without attracting any comments. Just decide.

**Comment by polx** [comment]
We are closing this issue having had too little echo: For most persons, it seems that it does not matter much which address is used; whether a software calls them "du", "Sie" or even "Du" does not matter and is often not remembered.

The "du" form was advocated sometimes ago and has been kept since then. This is continuing.

Should you feel that there are arguments for any of the alternatives. It would be very good to post them here as a comment (a closed issue can be commented). If you wish to activate the debate, please reopen this issue.

**Comment by solarkraft** [comment]
> to intrude into the personal space of the user, to insinuate friendship which is obviously a lie. We all know how disrespectful those companies really are.

As a young native German speaker having grown up embedded in international and US-centric circles, I find "Sie" to artificially *and disrespectfully* imply distance and coldness.
