### ISSUE TITLE
Implement user list & user colors

### ISSUE THREAD

**Issue by baldurmen** [xwiki-labs/cryptpad#26]
Hi!

Cryptpad is very nice, but one of the features I like from etherpad is that you can see other users when they open the pad and you can have custom colors for each user's modifications.

Do you plan on integrating these two things to cryptpad?

**Comment by ansuz** [comment]
Thanks for the feedback!

We have the first in the CodeMirror and CKEditor pads. You can set your name and see other user's names listed as they join. The interface is a button on the top left portion of the toolbar above the editing space.

Since you didn't notice it, I suppose there's a bit of a usability issue there. We can definitely see about making it more obvious.

For the second issue, I was an etherpad user before I started working on Cryptpad. I definitely see the value in having user colors. We've discussed it in the past but for now it's not very high on our todo list. It should be on the way, but at this point I can't say when.
