### ISSUE TITLE
Donation Page Lacks an Obvious Cryptocurrency Donation Method

### ISSUE THREAD

**Issue by gitjeff2** [xwiki-labs/cryptpad#262]
Maybe I've just missed it, but I don't see an obvious way to donate cryptocurrency to the project. It would be nice if the donations page supported this. If the issue is the crowd funding platform lacking support for it, at last stick a QR code with a donation address somewhere obvious on the main page.

Monero and Bitcoin are the obvious choices along with possibly Dash.

Very cool project.

**Comment by ansuz** [comment]
Hi @gitjeff2,

Thanks for the feedback, compliment, and interest!

We're planning to add more notices about our crowdfunding campaign so that it's more _obvious_ we need help. Currently, we have some information regarding donation on our accounts server, which is available here:  https://accounts.cryptpad.fr/#/donate

![screenshot from 2018-07-27 10-40-57](https://user-images.githubusercontent.com/1264398/43311229-1ce1f68c-918a-11e8-8a89-90942195c525.png)

I believe we can accept Bitcoin, Monero, Ethereum, and ZCash. If you'd like to make a donation in another cryptocurrency, we can certainly look into the logistics to make that possible.

**Comment by ansuz** [comment]
Our donation page now features detailed steps you can take to support us via cryptocurrencies.
