### ISSUE TITLE
New app idea : mindmaps

### ISSUE THREAD

**Issue by mrflos** [xwiki-labs/cryptpad#269]
Hello,  
Nice job with Cryptpad, it starts to have a lot of cool and simple to use apps, so many thanks!  
There is one kind of app that misses the collaboration and security features that cryptpad provides : an online mindmap editor that allows to create something together while brainstorming.  
Something like https://github.com/drichard/mindmaps but collaborative (demo : https://www.mindmaps.app/ ) or https://app.wisemapping.com/c/maps/3/try 

I understand that could be a lot of work, but still like the idea of having this inside cryptpad!

Best regards

**Comment by ansuz** [comment]
Hi,
thanks for the feedback, especially the example applications. Our current roadmap is defined on [our OpenCollective page](https://opencollective.com/cryptpad). Once the work we've planned for the coming year gets funded we'd like to allocate time towards either developing more applications, or improving our APIs so that it becomes easier for other developers to contribute applications.

**Comment by ldubost** [comment]
I've pushed a branch https://github.com/xwiki-labs/cryptpad/tree/markmap
which would include markmap-lib (https://markmap.js.org/repl) support to code pads
I don't think it's fully ready for being added and it's not really a mindmap pad also, but it's worth looking at.
One of the drawbacks is that it required a special build of markmap-lib so that it could be used in cryptpad using requirejs.

**Comment by subrico** [comment]
Hello,
Markmap and Mathjax seems to be integrated in cryptpad 3.20.
But how can we activate in code or slide ?
With this exemple : https://markmap.js.org/repl

Thanks

**Comment by ansuz** [comment]
[This document](https://cryptpad.fr/code/#/2/code/view/kmYt1-pxaMlinUl2+YQSLyZetKE2GJo9QtTlCQ8RNks/) illustrates a variety of rendering extensions for the code editor. Not everything is fully supported in slides, so if there's anything in particular that's missing please open a new issue.

**Comment by subrico** [comment]
BIG THANKS !
It's just what I need : to declare which markdown syntax I want to use.

**Comment by ansuz** [comment]
The syntax for `markmap` blocks in markdown can now be found in [our docs](https://docs.cryptpad.fr/en/user_guide/apps/code.html#markdown).
