### ISSUE TITLE
Spell-checker issues on Firefox

### ISSUE THREAD

**Issue by baldurmen** [xwiki-labs/cryptpad#27]
Opening cryptpad with Firefox 45.2.0, I can see the spelling mistakes I make but when I right-click on them, instead of the normal FF menu, I get the CKEditor "paste" menu.

IMHO, disabling CKEditor's context menu makes for a much nicer user experience.

**Comment by ansuz** [comment]
clicking while holding control bypasses CKEditor's context menu and uses the Firefox default. Currently this makes no difference for your use case, though, as the editor has spellcheck set to "false".

I'll test whether there are any problems with turning spellcheck on, and if not then we can deploy the change to [beta](https://beta.cryptpad.fr/pad/).

**Comment by ansuz** [comment]
This issue was addressed in our last release, [v2.15.0](https://github.com/xwiki-labs/cryptpad/releases/2.15.0).

Spellcheck is off by default, but you can turn it on in your settings page:

It includes a description of how you can use it.

![screenshot from 2019-01-15 10-55-06](https://user-images.githubusercontent.com/1264398/51175018-7a37bb80-18b9-11e9-9d44-db996b75e627.png)
