### ISSUE TITLE
I can open password protected documents

### ISSUE THREAD

**Issue by Franciscogva** [xwiki-labs/cryptpad#278]
I created documents with with a password.
I log in into my cryptpad with my username and password 
I double clikc on one of the document wich is password protect. I can open it without inputting the password

**Comment by ansuz** [comment]
Hi,

Our intent with password protection was to make it such that even if the URL for a document was intercepted in transit, the URL alone would not be sufficient to access its contents.

The reason you're able to access the pad without entering the password is that the first time you enter it (or when you create the pad) the password is stored in your CryptDrive (so that you don't need to remember potentially hundreds of passwords.

If you open the same URL in a private window, or using a browser where you aren't logged in, then you should be prompted to enter the password. If that's not the case, then that's certainly a bug.

We can update the UI to make it more clear that the password will be stored in your account's _keyring_. Otherwise, were you hoping to have the option _not to store the password_, and enter it every time?

**Comment by fdiluch** [comment]
Hi indeed
I noticed that when I m logged in into my personal pad,  I don't need to input password.
Ok make more clear since, as a non expert,  in other platforms it is how we are used to behave

**Comment by ansuz** [comment]
We added two warnings to the share menu to convey how passwords affect sharing some time late in 2019, both of which link to [the related FAQ entry](https://cryptpad.fr/faq.html#security-pad_password).

![Screenshot from 2020-05-29 12-38-58](https://user-images.githubusercontent.com/1264398/83283703-9fc11e80-a1a9-11ea-8041-c2f839f91fc4.png)

![Screenshot from 2020-05-29 12-39-10](https://user-images.githubusercontent.com/1264398/83283713-a2bc0f00-a1a9-11ea-9541-8f91dce2470f.png)

I think it's fair to close this since we haven't received any questions about passwords since then.
