### ISSUE TITLE
add self destruct option after 3 wrong password in document 

### ISSUE THREAD

**Issue by fdiluch** [xwiki-labs/cryptpad#279]
add self destruct option after 3 wrong password in password protected document. 
In order to avoid massive multiple attempts

**Comment by ansuz** [comment]
Hi,

With the way that password-protected-documents are implemented, this is a little complicated. URLs contain a seed which is combined with the password to yield the information necessary to retrieve the pad (its identifier on the server, and the cryptographic keys to encrypt/decrypt and sign new messages).

Since you only know the identifier of the pad when you possess the seed and enter the correct password, neither the server nor the client are in a position to know which file to delete. It's possible to re-use the same seed with different passwords, thus making it such that there are multiple correct answers. Some disk encryption tools use a similar approach to make it possible to decrypt a false disk image with a secondary password. If the owner of the disk is compelled to decrypt it, they can surrender the decoy password, and have plausible deniability that they are not hiding anything. We haven't exposed this functionality in an easy way, but it's possible.

By contrast, we could make it such that the server kept a lookup table of random identifiers to pad ids. Whenever you tried to access a password-protected-pad, you'd request it with that random identifier, and if you requested it enough times (maybe without some token that you'd only receive if you correctly retrieved from the document), then the server could delete the pad without your client ever learning what it was.

I'm open to hearing more perspectives on this, but such a feature would add a fair bit of complexity to the system, be less compatible with the plausible deniability scenario described above, and add the risk that collaborative documents otherwise in use by legitimate users would have their ongoing work destroyed by someone trying to access it. It's entirely possible that someone trying to guess a password was not being malicious, but just impatient (maybe you'd sent the link, but hadn't yet disclosed the password via another medium).

We happily include features with _super-spy-grade-security_ if there are no usability tradeoffs, but in this case I'm not sure we can do so without negatively impacting average users' experience.

**Comment by fdiluch** [comment]
Thank you for the detailed explanations. I Understand (I am not IT specialist) it is complex. 
In this case,  how long (or complex)  has to be the password so it is not cracked within a lifetime ?
I believe, in this case, a system blocking the access after 3 wrong trial (or something similar - 2 factors )  should exist and would bring a higher confidence in cryptpad

**Comment by mthld** [comment]
Hi,

There is plenty of articles on internet about proper password policies. As my colleague mentioned, the feature you are requesting add more usability tradeoffs than what's acceptable for us.
