### ISSUE TITLE
Cryptpad main page fine, but trying to create pad results in blank page

### ISSUE THREAD

**Issue by symgryph** [xwiki-labs/cryptpad#286]
I was able to browse several pages, create a user account, but when I create a pad, I just get a blank page. The first line of my config.js looks thus:

*/
var _domain = 'http://cryptpad.munnster.com:3000/';

// You can `kill -USR2` the node process and it will write out a heap dump.
//

this is my 'internal' domain and correctly resolves inside of my domain. All systems can ping http://cryptpad.munnster.com which resolve to internal.

Running under node 10.

**Comment by ansuz** [comment]
Hi,

`_domain` should be set to whatever the client browser will see. It's most likely broken because clients access the site over port 80 or 443, while the content security settings are telling it to only accept content over port 3000.

You should probably just drop the `:3000` from the end of `_domain`.

If you update this value, you may want to check that it's working with a private tab, as the HTTP headers which are likely causing the problem are cached by most browsers.
