### ISSUE TITLE
Feature Request: Calendar / Reminders

### ISSUE THREAD

**Issue by gitbugged** [xwiki-labs/cryptpad#304]
This might actually be a feature of the Kanban board. I just want to be able to set things I need to do on specified dates / times and to trigger an (optional) reminder which is sent to my e-mail.

As simple as this sounds, I've yet to find a working open-source solution out of the box.

**Comment by ansuz** [comment]
We have some plans to add notifications and reminders within CryptPad's interface, but we don't yet have any intentions to extend this via email.

Our reasoning is that notifications within the app are relatively simple to integrate without exposing more metadata. Email integration would require that the server know the user's email, which is currently not the case. Likewise, since the contents of the documents are encrypted, clients would need to reveal some information about their documents to the server in order to support this functionality.

Perhaps in the future we'll think of a privacy-preserving way to accomplish this behaviour, but I don't have any clear ideas on how to do so given the current state of our infrastructure.

**Comment by ansuz** [comment]
As to the matter of a calendar...

I'd be very interested to have a encrypted calendar application within CryptPad, but we don't yet have a timeline for when that could be done.

**Comment by ansuz** [comment]
We implemented a basic version of calendars in our last release, but they still needed a lot of testing. We've deployed a big update today which takes them out of BETA status. Registered users should find that a link to the _calendar_ app is now present in the user administration menu which is found at the top-right corner of the page.
