### ISSUE TITLE
Demonstrate privacy safety

### ISSUE THREAD

**Issue by fdiluch** [xwiki-labs/cryptpad#316]
What to reply to the people , whom I try to convince Cryptpad, when they ask: "Francisco, How can you be sure is sure ?"

The Privacy page says lot of things but demonstrate nothing:
No audit from a renowned entity
No direct straight forward link in the "pcryptpad.fr/privacy" page showing the open source code.

How, for a none IT expert, to be sure ? and to convince another non IT expert ?

**Comment by ansuz** [comment]
This is a complicated question since any answer will always reduce to either having the expertise to judge for yourself or to trust an expert. We plan to introduce a build system with reproducible builds in the future, and to load our javascript libraries using the relatively new [sub-resource integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) APIs, which would allow users to check that the hash of the javascript is listed in a registry of valid hashes. The problem here is that it guarantees you're getting a particular javascript file, but not whether that file is trustworthy or malicious.

As can be seen from our [opencollective campaign](https://opencollective.com/cryptpad) and our occasional [funding status updates](https://blog.cryptpad.fr/2018/12/09/CryptPad-funding-status-November-2018/), we're still trying to increase our revenue to break even against the cost of development. I don't think it would be a worthwhile use of the funds we have to pay for an audit, so the best we can do in that regard is to wait for someone to volunteer their services.

This GitHub repo is linked from the footer of every page, though I suppose we could link to it from the page content as well.

So, lacking any definitive proof that CryptPad is absolutely safe, I'd ask those who you want to convince what tools they currently use to collaborate. If they're relying on Etherpad or some similar tool which doesn't even claim to offer any privacy features, or on Google's tools (knowing that Google's business model is to exploit user-provided data), then even imperfect privacy features may offer a step in the right direction.

**Comment by fdiluch** [comment]
I have 2 questions in fact. 
1.
Is cryptpad well crypted so that I can be sure it is safe. You replied to that question. Noted that for the moment you cannot definitely proove it.

2.
As user of Google drive, I "feel" more secure regarding another person trying to access my data because it requires a 2 factor authentication : It sends me a code by sms to my phone. 
While with Cryptpad I feel less secure because it does not offer this feature. There is a password protection feature but If I leave my session open in my professional computer, someone reopening the browser can have access the password protected file because it does not automatically log out from the session ( like bank websites do after 5 min of inactivity).

**Comment by fdiluch** [comment]
You can take example of what Threema is doing:
https://threema.ch/en/blog/posts/audit19en

**Comment by mthld** [comment]
Hello, thanks for your interest in CryptPad!

We recently created a whole new website for the project: https://cryptpad.org. You can find various links in the footer, even to the source code of the software.

You can check out [our flagship instance](https://cryptpad.fr) Terms of Service and Privacy Policy right from the landing page. Also we will soon starting the process to document all the cryptographic side of CryptPad.
