### ISSUE TITLE
Android app

### ISSUE THREAD

**Issue by heyakyra** [xwiki-labs/cryptpad#332]
Aren't most people editing notes on the go nowadays? Most people can't use this due to design issues and lack of mobile apps (see #208)

**Comment by IPv777** [comment]
I agree, a mobile app could be very useful

**Comment by meximan** [comment]
This is awesome!

**Comment by cannycartographer** [comment]
Hi, did the progressive web app get to production ready? How can I use it?

**Comment by AnotherNeko** [comment]
I'm asking for an Android app because loading cryptpad in mobile web browser messes really badly with Android word correction engine (between the keyboard and the text field, it intercepts typed words and offers spelling suggestions and can do autocorrect.)  It makes typing cryptpad on phone really difficult, worse than the Github text field I'm typing into right now.

**Comment by JanuszKornath** [comment]
How ist the progessive web app coming along? Cryptpad relies heavily on right clicks and is far from usable on mobile.

**Comment by master-bob** [comment]
Hello,

I understand about making a PWA instead of a dedicated application. My concern is regarding transfer from other applications, for example if I have another (Android) app which has an automatic backup. I don't know if it is possible for the automative backup to directly link with the PWA.

Okay. Thanks.
