### ISSUE TITLE
Problem with Login after Logout

### ISSUE THREAD

**Issue by mp-4** [xwiki-labs/cryptpad#340]
**Prologue:**
I had a problem with my main account, so i created a new account with different username and password. I was definitively sure, that credentials were correct.  So something wasn right there i thought.

**Present:**
I was in my drive of my testaccount. Create a pad, wrote a some word, saved it and logged me out. 

Next step -> i wanted to log me in again. 
-> Problem i got the same error message, which i had got on my main account.  "Invalid username or password. Try again, or sign up" 

**Questions you might be have:**
_Did you change your browser to solve this problem ?_
Yes. I tried this on other browsers - Chrome, Firefox, IE, Edge and Firefox portable (because of plugins)

_What OS-platform and browser plugins i have?_
Windows 10 (up-to-date)
All browser up-to-date
Plugins: Disconnect, uMatrix, uBlocks Origin, Wappalyzer, https everywhere

_What did you before?_
1. Its happend on ~ March 14th.
2. I did some windows Updates.
3. I did a cleanup with the programm "ccleaner". (i deleted all cookies and other saved infos of browsers)
4. Restart PC and got this login problem.

**Comment by ansuz** [comment]
CryptPad sessions persist by setting a token in localStorage. I'm not sure how ccleaner works, but when you clear browser history manually it is normal that localStorage is cleared as well. As such it's expected that you'd have to log back in after clearing your cache.

I just created a test account, logged out, and logged back in without issue on both Firefox and Chromium on Linux. We haven't made any changes to our server since March 5th, so I don't think the timing is related.

When you say you're _definitely sure_ the credentials are correct, how do you mean? Was the password saved to a password manager or are you re-typing it from memory?

**Comment by mp-4** [comment]
I understand that i have to login again when the token is "gone". I expected that.

I use a password manager. Keepass

**Comment by mp-4** [comment]
Because you mentioned "Linux" - I started my virtual maschine and tried to log in on Ubuntu with the browser Firefox. 
And what should i said, it works with my main account (there was the same login-problem) ! 
(Test account is still not working, [but it is not on my top priority list, if this testaccount is gone])

After i thought the login-problem with my main account was solved another issue occurred.

My drive is empty! -.-

A message on the botton of the site showed up:
"The selected or last visited directory no longer exist. Opening the parent folder..." and
"Unable to open the selected category, displaying root."

ps.: should i create a new bug ticket or continue here ?

**Comment by MacLemon** [comment]
Hi, webmaster of that instance here.

The issue was that CryptPad wasn't able to find /block unless its path was explicitly stated in the `config.js` which wasn't the case for us, since it is a well worn instance and the necessity to change the config wasn't stated in the release notes.

The result was logins breaking for some accounts, and when we upgraded from 2.18 to 2.19 it broke for everyone.

The fix was to explicitly state all paths given in `config.example.js` in `config.js` and restart the service.


From my PoV this issue can be closed.

**Comment by mp-4** [comment]
@MacLemon thanks. it works again :) Drive with my data is back.

@ansuz Thank to you for your support! :)

**Comment by phoerious** [comment]
I'm having the same issue on a new instance, but blockPath is set in my config file. Any ideas what else might go wrong here?

**Comment by phoerious** [comment]
Update: it works if all paths are relative and within the base installation directory. I believe this is a bug, because I can see the blocks and blobs being created and everything else works as well, but as soon as I log out, I cannot retrieve them anymore.

**Comment by count0** [comment]
I'm seeing the exact same problem as @phoerious on a new instance.

**Comment by count0** [comment]
@phoerious I managed to fix this, simply by adding symlinks to the blocks, blobs, etc from /var to the base installation. This is due to nginx needing to access these files directly.

**Comment by phoerious** [comment]
Symlinks is not a solution. But if nginx needs to access to files directly, I'll have to add that to the config.
