### ISSUE TITLE
Editing a local file?

### ISSUE THREAD

**Issue by gregfr** [xwiki-labs/cryptpad#35]
Greetings!

Is there a way to use Cryptpad to collaboratively edit a file on the server?

Thanks!

**Comment by cjdelisle** [comment]
I'm afraid that's a bit beyond the scope of CryptPad because we prevent the server from accessing the content which is written. Theoretically one could do it but it means duplicating the client-side realtime synchronization and Operational Transform code (a.k.a. ChainPad) on the server, so it's not in the roadmap at this point.

**Comment by gregfr** [comment]
Thanks for your answer! I hope a server-side client will be available on day.
