### ISSUE TITLE
Date formats

### ISSUE THREAD

**Issue by philiprhoades** [xwiki-labs/cryptpad#361]
People,

Now that I have been able to get started - my first reaction is: CP needs an International Date Format option ie dates should be able to be displayed in this format:

YYYY-mm-dd HH:MM:SS

I can't see that this config is possible anywhere at the moment . .

**Comment by ansuz** [comment]
Could you be specific where you're seeing the date? The default titles for documents should already be in an international format: https://github.com/xwiki-labs/cryptpad/blob/master/www/common/common-hash.js#L491-L497

Otherwise, I think some dates might be displayed in the user's preferred format (configurable in their browser). Personally I think it's better to respect user preferences than to enforce a standard.

**Comment by philiprhoades** [comment]
From my drive, under "Documents", the file "What is CryptPad?" shows: "Last Access" and "Creation" dates of dd-mm-YYYY.

In my bash scripts I can control the format of course but in apps like RoundCubeMail I have to change the config in the server code.  The simple "date" command gives:

Wed Apr 24 00:02:18 AEST 2019

I will see if that can be changed from the system anywhere.  I wasn't suggesting enforcing anything, I was suggesting making the format user-configurable . .

![Screenshot_2019-04-24_00-03-48_CryptPad](https://user-images.githubusercontent.com/1153703/56587892-b0f24000-6625-11e9-8fb4-fcf5aecf1430.png)

**Comment by ansuz** [comment]
Those should match your browser or system's preferences. They're generated using either `new Date().toLocaleTimeString()` or `new Date().toLocaleDateString()`

**Comment by philiprhoades** [comment]
It is a major hassle to enforce iso8601 everywhere . . I will keep looking . .
