### ISSUE TITLE
Browser history includes hash

### ISSUE THREAD

**Issue by cyphunk** [xwiki-labs/cryptpad#372]
The browser history includes the hash part of the file. Is there an option to disable this from being included? I realize as I write this that this might not be supported in browsers? I see that send.firefox.com stores the hash as well. But if there is a feature to remove this part from being stored in history that would be helpful

**Comment by cyphunk** [comment]
Oh also it would be good if when the user is logged in that the decrypt hash is not included, and the user then clicks the share icon to get the sharable editable link with the hash. This would be similar to how google docs works.

**Comment by ansuz** [comment]
We've discussed making this a user-configurable option. When the project was started it wasn't so common for browsers to sync history with the cloud, nor were they so aggressive about getting users to enable cloud sync if it wasn't a default. Generally we consider securing against the user's browser outside of our ability, but this is something that we can realistically try to address, though it requires some work.

The main issue is that we probably still need to store _something_ to identify the document, otherwise reloading the page will cause the browser to forget what you were editing. We could replace the secret keys with an arbitrary token which only _that user_ will be able to link to that document, but since so many people are used to copying what they have in the URL bar and sending it to friends, this poses a bit of a usability issue by breaking common expectations.

In my opinion the best solution will be to leave some info in the URL which would allow visiting users to request access to the document in question without giving access directly. This could tie into the social improvements we've been making lately, but we're a while off from being able to integrate such functionality. In any case, we'll still need a plan for how to approach support for older documents.

**Comment by ansuz** [comment]
This has been fixed in our [LabradorDuck](https://github.com/xwiki-labs/cryptpad/releases/tag/3.11.0) release and deployed to https://cryptpad.fr.
