### ISSUE TITLE
Chat history doesn't delete

### ISSUE THREAD

**Issue by seylm** [xwiki-labs/cryptpad#378]
Private chat history says it's permanently deleted when clearing chat history, but returns when chat is reloaded.

**Comment by ansuz** [comment]
It seems as though this behaviour is related to our use of SharedWorkers. As far as I was able to tell the history is being deleted on the server but there's a local cache that only gets cleared when the sharedWorker gets shut down. This only happens when you close all your tabs, so I expect that if you totally exit CryptPad and come back, those messages will be gone.
