### ISSUE TITLE
Both master and 0.3.0 show the spinner forever

### ISSUE THREAD

**Issue by ochronus** [xwiki-labs/cryptpad#38]
I've tried both 0.3.0 and master with multiple storage engines - when creating a new pad/code editor the spinner shows up and keeps on spinning forever

**Comment by ansuz** [comment]
There was a version mismatch in one of our bower dependencies that caused loading to fail.

It should be fixed now. Try running `bower update` and reloading.

**Comment by ochronus** [comment]
Thanks, updated but in the meantime I debugged that the problem is 'WebSocket is closed before the connection is established' - though netstat says that everyting is running as configured:

`tcp        0      0 0.0.0.0:5000            0.0.0.0:*               LISTEN      16447/node      
tcp6       0      0 :::443                  :::*                    LISTEN      16447/node `

**Comment by ochronus** [comment]
After setting the websockets port to the same as the http port, it's now working

**Comment by ansuz** [comment]
Yea, that's still something of an issue for us too, so we're working on it.

Unfortunately our current infrastructure for Cryptpad.fr has required that we run apache, and apache doesn't handle websockets well (or at all, since we point to the nodejs server directly).

We're in the process of migrating everything to nginx. Once all those kinks are ironed out that will be our officially supported configuration, and we'll have documentation for how to set things up (beyond the nodejs process).

**Comment by ochronus** [comment]
Cool, thanks for the help and the heads up :)

**Comment by ansuz** [comment]
No problem, always happy to have more users :smile:
