### ISSUE TITLE
Increase file upload max size

### ISSUE THREAD

**Issue by fdiluch** [xwiki-labs/cryptpad#384]
Yesterday I wanted to transfer a file from google drive to cryptpad but I could not.
The file was 25 MO and the upload could not be done.
I want to have cryptpad to replace google drive and it is important to have at least the same functionalities

**Comment by ansuz** [comment]
We set it at its current value because we didn't want to deal with pirated movies or things like that. If we have to deal with takedown notices that will be time spent that isn't going towards building new features.

Since the only people with enough space to upload the sorts of files we'd expect to be pirated, and those people have their personal info associated with their accounts, I don't expect that it would cause problems to increase it for them.

So far the only difference for paying users is extra storage space, but we could consider this a premium feature.

**Comment by nocko** [comment]
As a current paying customer, I'd appreciate this. I want to use "Crypt Drive" to more securely share files with my customers and ran into the limit...

**Comment by ansuz** [comment]
We've added support for increased file upload size for *premium users*__*__ on our staging branch which we'll merge and deploy for our next release. We plan to increase the server-enforced size limit to 100MB, however, since encryption is done on the client the practical limit may vary according to available resources.

__*__ paying users on CryptPad.fr or users with an entry in the _customLimits_ attribute of the server's configuration on any other instance

**Comment by ansuz** [comment]
CryptPad.fr now supports file uploads of up to 100MB.
