### ISSUE TITLE
Size of Spreadsheets

### ISSUE THREAD

**Issue by hentai-kamen** [xwiki-labs/cryptpad#398]
On cryptpad, my spreadsheets are 150MB.

The same spreadsheet on Google Drive is 200KB.

Is this normal?

**Comment by DhruvTheEthDeveloper** [comment]
most probably , they are combining the size of  proof file generated by the trusted setup ( as they are using the Zero knowledge proofs). but i will audit the code and will tell the exact reason.

**Comment by ansuz** [comment]
Hi,

Google counts the size of content, which we can't do since we don't have access to the content. Currently, we count the size of the spreadsheet's history of changes which is made even larger due to some overhead introduced by the encryption layer.

In the future we'd like to decrease this overhead by dropping older history, but such features are time-consuming since bugs can result in data loss. We're currently tied up working on other features since our main source of funding only covers that development, but we hope to put spreadsheets back on our roadmap soon.

**Comment by ansuz** [comment]
By the way @DhruvTheEthDeveloper, zero knowledge proofs are a very different technology than what we're using. Zero-knowledge is also a term widely used to refer to cloud services which offer storage and connectivity with end-to-end-encryption and key management implemented client-side.

**Comment by DhruvTheEthDeveloper** [comment]
oh , actually i was working in the same field and thought that your project is using zksnarks and  other implementations for the implementation of the ERP solution. ok  will sure be  checking the code and see whether this tech will work or not.

**Comment by ansuz** [comment]
This issue is not specific to sheets, since every document type in CryptPad stores the history of edits and counts their overhead as part of its size. We've implemented the ability to trim documents' history to preserve only the most recent patches which are required to load them. This functionality can be found by opening the document's "Properties" menu by right-clicking it in the drive or by using the "File" menu inside the editor itself.

Since this option is provided, I'm going to go ahead and close this issue.

**Comment by MichaelSchriewer** [comment]
Just to add my current experience as a new Cryptpad user:

Found that - for unknown reason - the option to delete the history in the "Properties Dialog", mentioned above, does _not_ show up when I need it, but _does_ show up when I do not need it ;-).

So I currently use a _workaround_ by creating a copy of a file with boosted size. This removes the overhead.

Did some investigation on this:

- It seems that the issue appears when _formated_ cells are copied and pasted, while it does not appear when selecting unformated pasting.
- I found this issue also on other Cryptpad instances, using different browsers and different versions of OnlyOffice.
- In case the "Property" dialog does not do it's job, it is also possible, to _create a copy of the high sized file_ in order to reduce file size:

```
-> Original file size = 2.34 MB
- Pasted 10.080 cells (including text, formulars and formats)
-> New file size = 25.49 MB
- Created a copy of 25.49 MB file.
-> File size of the copy = 3.73 MB
```
