### ISSUE TITLE
Cannot access admin page unless server is run with `npm run fresh`

### ISSUE THREAD

**Issue by rainyday** [xwiki-labs/cryptpad#404]
Running the server normally, it is impossible to access the admin page.

I followed directions in the last comment on https://github.com/xwiki-labs/cryptpad/issues/363 and starting the server with the `npm run fresh` command allows access to the admin page, however even after flushing the cache, restarting the server normally with `node server` goes back to being unable to access the admin page.

**Comment by cremesk** [comment]
same here. thanks for the tip!

**Comment by ansuz** [comment]
When you run `node server` the server uses the version found in package.json as a cache-busting string. `npm run fresh` causes a new cache-busting string to be used for the duration of that server process's lifetime, and `npm run fresh` causes each page load to fetch new version of files.

Your difficulty with the admin page should go away the next time you update your CryptPad instance, or if you used a different browser or a private session.

This is all intended behaviour, since we figured that admins would not necessarily want all their users to have to reload static assets just because the server was restarted. In practice, I think lots of admins have problems with this, so maybe we'll just make the _fresh mode_ behaviour the default and make the current behaviour something you'd have to force.

Thoughts?

**Comment by ansuz** [comment]
"fresh mode" is now the default behaviour on our staging branch, so our next release will fix these types of issues. The current behaviour of using the version from package.json as a cache-busting string can still be invoked by launching the server with `PACKAGE=1 node server`.
