### ISSUE TITLE
Firefox jumping to beginning of the page whenever style is changed

### ISSUE THREAD

**Issue by frlen123** [xwiki-labs/cryptpad#406]
I think this might be a minor bug, but when using Firefox (Win 10, 64 bit) and changing the color, background-color, paragraph format, font, or basically any of the parameters of the top Menu of a Rich Text pad, the window will scroll to the beginning of the document (something like `window.scrollTo(0,0)`). So whenever I do one of these changes, I need to manually scroll back to where I was in the page (although selections and cursor position are preserved).

I get this message in the console:

> Request to access cookie or storage on “https://sandbox.cryptpad.info/common/feedback.html?CKE_BUTTON__TEXTCOLOR=c666685a1601d” was blocked because we are blocking all third-party storage access requests and content blocking is enabled. pad

Clicking on "Learn more" leads me here:
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Privacy/Storage_access_policy/Errors/CookieBlockedForeign?utm_source=devtools&utm_medium=firefox-cookie-errors&utm_campaign=default

**Comment by ansuz** [comment]
Thanks for the detailed report.

The message in the console seems related to our feedback system which we use to gauge which buttons people actually use so that we can simplify the interface. The message text is misleading because it's not accessing third-party storage and no content is actually loaded. You can disable this feedback via the [settings page](https://cryptpad.fr/settings/). Please let us know if doing so stops the cursor from being disrupted, as the editor's behaviour should not be affected by the feedback system.

**Comment by frlen123** [comment]
Thanks for the prompt reply! I disabled it, but I still have the weird scroll to the top behaviour.

**Comment by jonasdagefoerde** [comment]
Same problem on OSX 10.15.4 with FF 75.0: the window scrolls to the very top when formatting the text as described above.

**Comment by ansuz** [comment]
This has been addressed in our `main` branch and deployed as part of our [3.20.0 release](https://github.com/xwiki-labs/cryptpad/releases/tag/3.20.0). If the problem persists please reopen this issue.

**Comment by kertase** [comment]
The issue still exist when adding links and comments in firefox 85 but not in chromium.
Cryptpad 4.2.1

**Comment by Adrien-Luxey** [comment]
Same issue, but I see no comments in the console after disabling Firefox modules that were throwing some.

* Linux Mint 20.1
* Firefox 86.0
* CryptPad v3.19.0
