### ISSUE TITLE
Anchors don't work

### ISSUE THREAD

**Issue by frlen123** [xwiki-labs/cryptpad#407]
I'm not sure whether anchors have been fixed, this issue: https://github.com/xwiki-labs/cryptpad/issues/169 didn't make it clear for me. I'd just like to mention that adding anchors to a Rich Text pad brings with it 2 problems.

1- they seem useless, because even when I create a "Link to anchor in the text", when I click on it nothing happens

2- adding an anchor also adds an img of a red flag and then the user gets this message: 

> This pad contains images stored in an inefficient way. These images will significantly increase the size of the pad in your CryptDrive, and make it slower to load. You can migrate these files to a new format which will be stored separately in your CryptDrive. Do you want to migrate these images now?

But no images were added to the Rich Text pad, just an anchor was added

**Comment by polx** [comment]
Besides the problem with the image storage, the anchors "just worked" with only this function: insert a named anchor, get an anchor in the exported HTML. There is no function yet for navigating within CryptPad as far as I know. Maybe works around #399 may help...

**Comment by ansuz** [comment]
@polx is correct that anchors only function within exported HTML, since their usage for navigation during a real-time session would interfere with our usage of the fragment identifier (`#`) for relaying other information.

I don't have any good ideas for UI hints to convey this to users. I understand it can be frustrating to have a button that doesn't  seem to work, so I'm inclined to just remove the button.

Thoughts?

**Comment by polx** [comment]
The ideal situation is that the frag-id and a possible inner location live peacefully together.
This way I can exchange URLs and invite people to go directly to somewhere.

However, I'm inclined to say that it would be enough to simply have anchors and table-of-contents to be working internally: a click to a link goes there, inserting a link offers the anchors as possible endpoints.
Am I right, @ansuz  that this would be easier to implement?

**Comment by frlen123** [comment]
Forgive me if it's a stupid suggestion, but can't javascript solve this? Like polx mentioned, the fragment could perhaps be split in 2. For example, `URL#hash--anchor`. JS could be used to get the fragment's last part (the `anchor` part) and then scroll to that element's position https://stackoverflow.com/questions/8070639/find-elements-position-in-browser-scroll

**Comment by polx** [comment]
You can do a lot in programming javascript.
However, you need to do it right and make sure it works right in many situations.
The frag-id 'peaceful collaboration' is complex because it involves not only the CKeditor part, it also involve the security layer where the key is read and written. As per design, the two layers live in different domains; this means that such an integration requires APIs between the two layers.  It's not impossible but it probably needs an entry into the roadmap before it is started.

**Comment by ansuz** [comment]
We've implemented a fix and deployed it to CryptPad.fr. It will be included in the upcoming release (4.5.0) which will be published as soon as I finish writing its release notes.

**Comment by feadi** [comment]
Hi!
Can somebody explain me how to use anchors?
When I create a link to one and click it nothing happens.
I really need anchors or some other kind of link to certain pages in documets to make cryptpad useful for me.
Thank you!

**Comment by ansuz** [comment]
> Hi! Can somebody explain me how to use anchors? When I create a link to one and click it nothing happens. I really need anchors or some other kind of link to certain pages in documets to make cryptpad useful for me. Thank you!

[This pad](https://cryptpad.fr/pad/#/2/pad/view/5JeZJ+7r+USdqQe0JN2AxxuIjoLjE0Y4OVsjvuWln5M/) demonstrates the supported behaviour. The table of contents on the left is generated based on the structure of the document. Clicking on an entry in the table of contents should scroll the document such that the corresponding section is visible. Headings are automatically included the table of contents, and anchors allow for content of other types to be navigable in the same manner.

**Comment by feadi** [comment]
Great! Thank you!
Is there a way I can link directly to an anchor? Like https://cryptpad.fr/pad/#/2/pad/view/FQZM1ZM8YbsLhkkfH3T/#anchor02
We are working on big documents and we need to be able to send links to certain parts. By email, chat or for jumping inside the document.

**Comment by ansuz** [comment]
Not currently. We do plan to add this functionality at some point in the future, but our roadmap is currently full with other features that have been funded through research projects or sponsored development.

**Comment by braniti** [comment]
Dear Ansuz, developers &  contributors .  
   First  thank  you for developing this  Open tool .

Today i discovered that anchors do Work ,  now i can introduce Cryptpad  to kids at our high school !!  
This was core issue for me to fully move away from Google docs, i could only use it for basic docs.

I learned  about your tool from mr. "feadi" about  2-3 moths ago  ( he has  recent comment in this thread ) . Back then this did not work  and we both needed this option. 
   I accidentaly noticed today that you fixed this ... , after  pressing CTRL+K to insert URL  link i think i spotted something changed in the pop-up screen compared to  few months ago ,so i tried instead of insert  URL to choose "Link to Anchor in text" option ,    and  it works !!  
   Ansuz, If you are heading to Amsterdam / Holland let me know ,  you are welcome 4 dinner @ our  place .
   Best ,
   B.

**Comment by 64mb14rr4** [comment]
Anchors don't seem to work (anymore?).

![image](https://github.com/cryptpad/cryptpad/assets/106013305/692a416e-405f-4275-bdfe-432ab99bdc83)

Nothing happens when clicking on the link (Firefox). :/

However, thanks for this great tool!
