### ISSUE TITLE
How to prevent brute force attack against user name and password

### ISSUE THREAD

**Issue by mason1900** [xwiki-labs/cryptpad#408]
As I am planning to set up an Cryptpad instance for my organization, I am curious about how do you prevent brute force attack against the user name and password. Because you are not using something like a reCAPTCHA, and you do not require an email address to register, how do you ensure that an malicious hacker cannot just brute force the password if they know the user name?
Thank you.

**Comment by ansuz** [comment]
Hi,

Login and registration in CryptPad are implemented client-side using the [scrypt](https://github.com/dchest/scrypt-async-js) password based key derivation function. Scrypt is explicitly designed to take a long time to compute, making brute-force attack expensive.

We pass three inputs to scrypt:

1. the user's password with no upper limit on its length or character sets
2. the user's name (as a salt)
3. a server-wide string which is added to the salt

Scrypt outputs a stream of bytes from which we derive a deterministic location for an encrypted blob and the keys used to encrypt and decrypt that blob. That blob then contains the keys to your drive.

This means that if someone wanted to brute-force usernames and passwords:

1. they would need to do so on a per-server basis because of the salt [which should be configured by the instance administrator](https://github.com/xwiki-labs/cryptpad/wiki/Application-config#configloginsalt)
2. they would need to know the user's username (which can differ from their current display name)
3. they would need a lot of time (password-space multiplied by the time to check one password)
4. they would need to connect to the server for each attempted password to see if an encrypted blob exists in the derived location

The fourth point makes brute-force attempts detectable by the server, since it would be possible to see a very large number of 404s in the `/block/*` URL path which serves the encrypted credentials.

Some security researchers have proposed using something called **verifiable delay functions** as a puzzle for clients which make too many requests. These puzzles are trivial to verify but difficult to compute. We could implement this in CryptPad by requiring clients to request such a puzzle from the server before they could attempt to access encrypted credentials. At the moment the main obstacle to doing so is the lack of a trusted implementation of a VDF in javascript  (since I last checked).

This is a tricky problem-space, since the usual methodology (CAPTCHAs or 2FA) typically rely on centralized third-party services that enable the kinds of surveillance we're trying to avoid. I'm actively following research in the field, but improvements in this domain aren't on our roadmap at the moment.

**Comment by mason1900** [comment]
Thank you for your explanation.

**Comment by jasonbrown1965** [comment]
Nice transparency, thanks.

Was initially alarmed at the idea of usernames in salts,
 but googed hash salt usernames and that explained how 
user names help connect salt to hashes, for any other
amateurs like me looking into security issues on git 

- here's a non-goog [startpage](https://auth0.com/blog/adding-salt-to-hashing-a-better-way-to-store-passwords/) link for same search - also has same top article in SP
