### ISSUE TITLE
FEATURE REQUEST: Color by author

### ISSUE THREAD

**Issue by patcon** [xwiki-labs/cryptpad#41]
I see that it's possible to name collaborators, but it doesn't seem that it's currently possible view edits by author. Is that something on the roadmap?

Thanks for this wonderful amazing tool! I have somehow convinced a friend to use it to set me up on a blind date, as an easy way to talk first but arrive with zero-knowledge (ha!)

**Comment by ansuz** [comment]
Thanks for the feedback! 

I hadn't considered Cryptpad as a dating site, but I imagine people will find all sorts of imaginative use cases when you provide a multi-user tool.

User colors were [requested before](https://github.com/xwiki-labs/cryptpad/issues/26), but they are not currently in our roadmap. As far as I know, etherpad's implementation of user colors is the exception, rather than the rule (in the realm of collaborative real time editors).

We have discussed sharing a user's cursor location (or at least which line they're editing on), but at present there are many more features that we'd like to implement first.

Once we've polished off the really rough edges (there are still more than I'd like), we can see about adding what I feel is an enhancement.

**Comment by pojebunny** [comment]
As the text in Pads is formated with HTML, you can add "classes", that included users name, to lines of text (or divs) + a small bar on the left side of the window where you can draw first letter of the users name or their chosen color.

**Comment by pbondoer** [comment]
I want to add to this in case it gets done - on an accessibility level, I think it's best not to rely only on colors and at least allow it to use the first few letters of the chosen name or some kind of readable ID so color-blind users may also fully enjoy the use of the editor.

**Comment by ansuz** [comment]
This is still low priority for lots of complicated technical reasons that are unfortunately very difficult to explain and very closely related to the way changes are integrated by clients in our architecture.

That being said, I appreciate the point about accessibility, and I'll definitely keep that in mind if we get around to this.

**Comment by sachaz** [comment]
+1 like Etherpad it's very usefull for collaborative work, like a timeline of the changes.

**Comment by ansuz** [comment]
We're working towards supporting this in our rich text pad, but unfortunately there are some low level issues we have to work out first. I can't really give a timeline for when to expect it, but it's on the way.

**Comment by sachaz** [comment]
Why this request is closed and not kept as enhancement ?

**Comment by ansuz** [comment]
This request is open, but I closed the duplicate. It looks closed because of github's confusing UI.

**Comment by imp1sh** [comment]
+1

**Comment by fauno** [comment]
meanwhile people can paint their changes with the background color button :P

**Comment by xshadow** [comment]
+1 

That is indeed the biggest drawback when switching from etherpad-lite

**Comment by dpausp** [comment]
We are considering CryptPad as replacement for etherpad, but missing authorship colors are a blocker for us. The solution in https://hackmd.io is interesting and may be better than etherpad-lite: the color of the first author is used for the left border, insertions by different authors are underlined.

**Comment by patcon** [comment]
Just a heads up about the community vs enterprise licensing stuff that hackmd moved towards: https://github.com/hackmdio/codimd/issues/579

**Comment by cjdelisle** [comment]
For your information, we're doing a fund drive to keep CryptPad completely free and one of the goals on our fund drive is color by author: https://blog.cryptpad.fr/2018/07/13/CryptPad-Roadmap/#Goal-7-Color-by-author
Please consider going to https://opencollective.com/cryptpad and donating what you can to help make this happen.

**Comment by Rik44444** [comment]
+1 i'd like to use Cryptpad, its rich-text support is amazing, but this is a blocker for me. I need to be able to see some form of tracked changes in the document.

**Comment by Rik44444** [comment]
to add, and i know this is likely impossible, but if you would be able to add some form of Track Changes, so not only colours, but tracking the changes people make (also deleting text etc), that would be amazing.... It would make cryptpad my goto collab site

**Comment by makefu** [comment]
I'd also love to see this feature added to cryptpad. For our podcast we used etherpad for our show notes and this feature became very handy. We try to switch to cryptpad, mainly because it is still supported, but reading the show notes in the show is not super convenient.

Is there a chance to directly fund this feature instead of going through all the other gates before?

**Comment by Rik44444** [comment]
just a note to help you: Smashdocs has all these functions! i discovered it recently, works really well!
https://www.smashdocs.net/ 
free but not open source or encrypted

**Comment by sachaz** [comment]
> free but not open source or encrypted
Hahhaha really funny ! 
It's just not acceptable for us to use a non open source project. Etherpad is still a good choice

**Comment by makefu** [comment]
> > free but not open source or encrypted
> 
> Hahhaha really funny !
> It's just not acceptable for us to use a non open source project. Etherpad is still a good choice


It is exactly the same case for us! Etherpad is still fine even though it is discontinued from development.

**Comment by ansuz** [comment]
> Is there a chance to directly fund this feature instead of going through all the other gates before?

@makefu Opencollective allows you to add a _Public message_ when contributing. If you say that you want a contribution to fund author colors we'll reserve your contribution towards that sub-project.

I'm curious whether people asking in this thread are interested primarily in having colors for rich text, or whether there's also interest in having it for the code editors. We'll most likely do both, but it would be nice to understand the use cases better.

**Comment by dpausp** [comment]
We only use the code editor (for Markdown) in the German Pirate Party and we have a high demand for author colors. I hope that we can provide some funding for the feature.

**Comment by makefu** [comment]
@ansuz We are also are only using for the code editor. We do not use the rich text editor but instead directly write in markdown. 

This is the source of our last show "Binärgewitter Talk 226: bastelt schöne Filter" in cryptpad https://cryptpad.piratenpartei.de/code/#/2/code/edit/K9zaDVi9Emp476p2OMaosU3u/

And this is the source of our last show we wrote together in etherpad (Number 214): https://rtt.piratenpad.de/249

As you can see, in the etherpad we can see directly in the show who wrote the news, a feature we dearly miss in cryptpad

**Comment by Rik44444** [comment]
@ansuz i would ise the rich text editor

**Comment by hannesss** [comment]
+1, this is the last blocker for our organizations to use cryptpad.

We would mainly use it for the markdown / code editor, as most of our members are used to it and also non techies easily learn it.

**Comment by madmas** [comment]
> +1, this is the last blocker for our organizations to use cryptpad.
> 
> We would mainly use it for the markdown / code editor, as most of our members are used to it and also non techies easily learn it.

In that case, has your company considered to sponsor the development of this issue?

**Comment by Wikinaut** [comment]
+1.

Lack of authors' colours is _the_ blocker for us here to use Cryptpad.

**Comment by rakta** [comment]
@ansuz we at SystemChangeNotClimateChange also miss the feature in the markdown editor to see, who contributed a certain part to a text. That's why we still use etherpad for most collaborative texts.

**Comment by Rik44444** [comment]
@rakta does etherpad do this...>?

**Comment by ansuz** [comment]
After lengthy discussions many of our users have clarified that what they want is not necessarily _authorship colors as implemented in Etherpad_ so much as the ability to review changes. On that note, we are waiting to hear back about a grant proposal which would fund the development of some features in that direction, rather than authorship colors.

_"Versioned links"_ will allow users to link to particular points in the history of any document, much like how GitHub allows for you to view a repository at the time of any one commit. This is a necessary component to allow us to implement a _diff view_ in the future.

_"Semantic history"_ would improve our existing _history mode_ by grouping changes to the document according to a variety of metrics such as their date, the identities of the editors online when the changes were made, and whether the changes affected the same or different parts of the document.

Finally, we'd like to implement _comments_ as featured in a number of other advanced collaborative editors. Comments annotate parts of the document and allow users to point out flaws, request review, or mark existing comments as resolved.

I think that these features combined together offer users a greater ability to review their documents' evolution, especially combined with our existing notifications system which we continue to improve. As far as I've seen the other collaborative editing platforms on the market do not implement authorship colors either (except Etherpad), while many of them do offer comments and advanced history modes.

**Comment by T3rminat0r** [comment]
I'd actually like the Authorship Colors, as seen in Etherpad, i.e. you can see who wrote which entry on a collaborative shopping list, etc. (without having to dig through some lengthy edit history)

**Comment by ansuz** [comment]
Our staging branch has an experimental version of authorship colors. We built on top of [this PR](https://github.com/xwiki-labs/cryptpad/pull/522) to translate a few things and handle a few edge cases with concurrent edits. It's still not perfect when lots of people are editing at once, but it's probably enough to address most few use-cases.

We've been procrastinating on this issue for a long time. Everyone who's been waiting for this feature owes a big thanks to @stoppegp and @promasu for developing a prototype and coordinating with us to get it finalized and merged.

**Comment by xshadow** [comment]
That sounds very interesting.

**Comment by ansuz** [comment]
![Screenshot from 2020-04-21 13-03-37](https://user-images.githubusercontent.com/1264398/79892409-8a015200-83d0-11ea-8d8b-1cca3e016023.png)
