### ISSUE TITLE
cryptpad docker image starts node server.js as root

### ISSUE THREAD

**Issue by zem** [xwiki-labs/cryptpad#421]
See output: 

root@docker1:~/docker_compose_ports/cryptpad# ps -eaf | grep node
root     11981 11828  0 21:25 ?        00:00:00 node ./server.js
root     12231 31375  0 21:30 pts/0    00:00:00 grep node

I am not as familiar with node.js but in my experience having something started as root means that it could (theoretically) modify its own binarys if it contains an error. As we all know that software has errors, it would be best to introduce a UID within the container under which node.js will be started.

**Comment by ansuz** [comment]
My understanding of docker is that even as root the process should only be able to affect files located in the container or in the directories shared between the container and the host platform. If that's correct then it shouldn't be a risk, but I'm no docker expert.

In any case, I'm happy to merge a PR fixing this. We don't use docker ourselves so any provided configuration is purely maintained by the community.

**Comment by ovizii** [comment]
Here's a nice article explaining why its "safer" to not use root: https://americanexpress.io/do-not-run-dockerized-applications-as-root/

**Comment by mason1900** [comment]
Advice: you may want to look into the Docker files of `privatebin`. Their code and instructions regarding Docker was very well written.

**Comment by ansuz** [comment]
Hi folks.

I only ever included the docker-related files in this repository because people who were maintaining their own Dockerfiles wanted to share them. Our development team does not use docker at all, so any updates to this are going to have to come from the community. We've been discussing moving everything docker-related from this repository and into its own repo, since having them here implies that they are actively supported.

In the meantime, I'm going to close this and propose that somebody submit a PR to fix the issue.
