### ISSUE TITLE
Install issues 

### ISSUE THREAD

**Issue by fredhampton** [xwiki-labs/cryptpad#43]
We want to run an instance of cryptpad for our coop members
We have installed but when we start the app we have a page that has the cryptpad logo but no functionality.

What are the required changes to the config file to run cyptpad in production ?
Is mongo db required ?
How can we change the look and feel if needed ?

Thanks

**Comment by ansuz** [comment]
It's possible the clientside dependencies weren't installed correctly. In the root directory, run `bower install`.

If you don't have bower installed on your system, run `npm install -g bower`. Depending on your setup, this may need to be run as root.

Settings which are meant to be configurable (stylesheets, translatable interface text, etc) are located in `cryptpad/customize.dist`. Rather than modifying these files (which would result in merge conflicts when updating), make a new directory named `customize` with `mkdir customize`. If you want to override one of the default files, copy it to `cryptpad/customize` and modify that version. The server will prefer to serve files located in that directory.

**Comment by fredhampton** [comment]
Thanks !!!! I will give this a try 


On October 6, 2016 at 2:05:17 AM, ansuz (notifications@github.com) wrote:

It's possible the clientside dependencies weren't installed correctly. In the root directory, run bower install.

If you don't have bower installed on your system, run npm install -g bower. Depending on your setup, this may need to be run as root.

Settings which are meant to be configurable (stylesheets, translatable interface text, etc) are located in cryptpad/customize.dist. Rather than modifying these files (which would result in merge conflicts when updating), make a new directory named customize with mkdir customize. If you want to override one of the default files, copy it to cryptpad/customize and modify that version. The server will prefer to serve files located in that directory.
