### ISSUE TITLE
Can edit read only doc

### ISSUE THREAD

**Issue by AndrewJ-Cpad** [xwiki-labs/cryptpad#440]
When you open a document in read only mode, and not share it in embed mode (with toolbar, etc hidden), then the page opens it int read-only, but the propoerties button on the right shows the user a link to the editable document - so anyone displaying the document in read mode should beware that the user can access and edit the document by cutting and pasting that link into their browser.  I would think that in read-only mode there should be no access to edit the document.

**Comment by yflory** [comment]
You can only see the "edit" link if the editable version of the pad is already stored in your CryptDrive.
It won't be displayed in the properties popup if you've only received the "view" access rights from a friend. There is no way to recreate the "edit" link from the "view" one.

**Comment by ansuz** [comment]
We discussed adding a warning to the sharing menu when in the view mode of a document for which you have edit access, like so:

![share modal mockup](https://user-images.githubusercontent.com/1264398/84180561-b858f080-aa55-11ea-9cf3-e7663f1142b7.png)

In the end we decided against it because there are already a number of similar warnings and we want to avoid [alert fatigue](https://en.wikipedia.org/wiki/Alarm_fatigue). We're in the process of writing a lot of documentation and we'll include a section which explains this behaviour.
