### ISSUE TITLE
Question about anti-abuse

### ISSUE THREAD

**Issue by mason1900** [xwiki-labs/cryptpad#444]
In [your blog](https://blog.cryptpad.fr/2017/07/07/cryptpad-analytics-what-we-cant-know-what-we-must-know-what-we-want-to-know/) you said that one malicious attacker created 647,533 pads. I am curious about:

1. how did you detect such malicious behavior (as CryptPad is a zero knowledge service)
2. how did you know that these pads came from the same person
3. what kind of tools or commands did you use to select and clear out those spam pads

Thanks!

**Comment by ansuz** [comment]
Hi,

1. We use ElasticSearch and Kibana for analyzing our server logs to see things like how many unique IPs visited CryptPad. We don't sell this data or share it with anyone outside our small team. We mostly use it to see which applications in CryptPad are most popular to decide where we should focus our efforts.

2. We looked at Kibana and saw a large increase in page loads, so we investigated the cause. There were a lot of requests for one particular page, so we filtered out everything else and quickly noticed that most were from one IP address. From there we filtered out that IP which allowed us to get a count on the number of requests which we mentioned in the blog post.

3. We didn't need to clear out "spam pads", because as the blog says:

> They didn’t put much thought into their attack because what they were doing was not actually creating pads

They were loading the `index.html` part of the page, which is not the same as creating a document on our server. Serving static HTML is very easy for us to manage as it doesn't relate to the database at all.
