### ISSUE TITLE
does not work in chrome

### ISSUE THREAD

**Issue by red667** [xwiki-labs/cryptpad#450]
Hi,

I just updated cryptpad and also changed from apache to nginx.

Now I have the Problem, that cryptpad only works in firefox, ie and safari but does not in any chrome bases browsers.

I used the config templates from github, and did not make any changes except for the domains.

Has anyone experienced this problem and can point me to the solution?

**Comment by ansuz** [comment]
We've made a lot of updates to the example.nginx.conf file provided in docs, notably introducing the use of domain variables for all the CSP settings. I'm using it for my own personal CryptPad instance and it works as expected.

Since this issue is a few months old and it predates these changes, I'm going to close this. If you try using the most recent version of the example config and still have issues feel free to comment again.
