### ISSUE TITLE
Unable to access via school network

### ISSUE THREAD

**Issue by JtLively** [xwiki-labs/cryptpad#47]
When users visited a link to a Cryptpad, the page stalled with the loading GIF and never displayed content.

**Comment by ansuz** [comment]
We're currently working on a migration to a new server that will use Nginx instead of Apache.

Nginx has much better websocket proxy support, which means that client's connections will happen exclusively over port 443.

This should address your problem. If you'd like to test, you can visit the server that we're migrating to, at https://new.cryptpad.fr. To warn you, though, **data on that server will be deleted before we migrate**, so it is strictly for testing purposes.

**Comment by JtLively** [comment]
Thank you. Estimated time until completion on migration ? Will there be any 24/12/2 hours warning in the GUI pre-removal of content ?

**Comment by ansuz** [comment]
Migration tests went smoothly today, so the plan is to migrate tomorrow morning, 10am (Paris time).

I'll put up a notice 1 hour beforehand, and it should be done by 10:30, at which point it will have the complete dataset from Cryptpad.fr. Data currently on new.cryptpad.fr might get erased at any time.

**Comment by JtLively** [comment]
Sweeet. I'll keep using it for current projects then.

**Comment by ansuz** [comment]
Migration completed. If you can confirm that it works at your school, we can go ahead and close this.

**Comment by cjdelisle** [comment]
# If you could go ahead and test the new version.... that'd be great
![lol](https://uproxx.files.wordpress.com/2015/02/bill-lumbergh-office-space.jpg)
# And I'll go ahead and close the issue

**Comment by JtLively** [comment]
Only worked on Chrome. Firefox and Edge had seemingly JS issues. Firefox wouldn't even show the buttons. I had to type "cryptpad" /poll, /slide, etc.. There were no issues on IE, though. All notes are in IRC.

**Comment by ansuz** [comment]
I believe you said on IRC that this issue resolved itself, so I'm going to close this.

If I'm misremembering we can open it again.

**Comment by JtLively** [comment]
Yes it's good now.
