### ISSUE TITLE
Vulnerable JQuery 2.1.4

### ISSUE THREAD

**Issue by kravietz** [xwiki-labs/cryptpad#471]
`https://cryptpad.fr/bower_components/jquery/dist/jquery.min.js` is JQuery 2.1.4 which contains known vulnerabilities dating back to 2015. More information:

https://snyk.io/test/npm/jquery/2.1.4

Tactical solution would be to upgrade to latest 2.x which is https://code.jquery.com/jquery-2.2.4.min.js

Strategic solution would be to run OWASP Dependency Checker on your code base during build to make sure all dependencies are up-to-date.

**Comment by ansuz** [comment]
Thanks for looking into it. A quick scan of the repository indicates we don't use jQuery's ajax functionality anywhere in CryptPad. We do use `$.extend` in a few places, however, I don't think it's used in a manner that would enable the proposed attack methodology

> The `extend` function can be tricked into modifying the prototype of Object when the attacker controls part of the structure passed to this function

I'm pretty sure even if you could manipulate a session into modifying the Object prototype, it would only apply locally, not to remote sessions. If you can propose a counter-example please inform us via contact@cryptpad.fr.

Thanks again.

**Comment by kravietz** [comment]
@ansuz Would that be so much of a problem to just upgrade from `2.1.4` to `2.2.4`, or are you specifically bound to the old version?

**Comment by ansuz** [comment]
I haven't investigated the issue in much depth yet, but I don't expect there are any barriers to updating. I just wanted to respond to this issue to clarify that just because JQuery is vulnerable to certain classes of attack doesn't necessarily mean that _CryptPad is_.

Many of our users follow these issues and I wouldn't want them to worry that their information was vulnerable without justifiable cause beyond a warning message which is incomprehensible for most audiences.

Since it doesn't seem to be urgent I'll prefer to wait until the coming week to deploy the upgrade.

**Comment by kravietz** [comment]
@ansuz Sure, that makes perfect sense! 

The only reason for my persistence is that I've seen many projects dismissing reports about easily fixable and old security issues because they were "not exploitable" at that moment, only to find themselves adding functionality that makes them exploitable shortly after...

**Comment by ansuz** [comment]
I've updated the version in our `bower.json` file and pinned it to 2.2.4. We'll continue to test for the remainder of this week in case there are any subtle regressions, but after some quick testing everything seems ok. I expect to include this change in our next release (3.7.0) which will be tagged and deployed on December 10th.

**Comment by ansuz** [comment]
Thanks for notifying us of the possible issue!
