### ISSUE TITLE
privacy.html  -Links to other Site-

### ISSUE THREAD

**Issue by CheatCoder** [xwiki-labs/cryptpad#473]
is there a way to change the "CryptPad.fr" on a Self hosted server.
![cryptpad](https://user-images.githubusercontent.com/6120746/70373266-f418cf00-18e7-11ea-98a9-ab8b0e64eee0.png)
 
Should it not use the _domain from config.js?

**Comment by ansuz** [comment]
We left it as is because we felt this page is more a legal policy for the host than a technical policy that we can enforce through code.

This page is customizable (see [our wiki page about customization](https://github.com/xwiki-labs/cryptpad/wiki/Customizing)). In particular, you'll want to override the translation keys via [this file](https://github.com/xwiki-labs/cryptpad/blob/master/customize.dist/translations/messages.js). You can see what translations keys are used [here](https://github.com/xwiki-labs/cryptpad/blob/master/customize.dist/pages/privacy.js), and even modify the logic of the file further if you want.

**Comment by MacLemon** [comment]
We just redirect requests to our organisations privacy policy page in nginx like so:

```nginx

        # Redirects the Privacy Policy to the C3W Datenschutzerklaerung
        location = /privacy.html {
                return 302 https://example.com/privacy/;
                add_header Referrer-Policy "no-referrer" always;
        }
```
