### ISSUE TITLE
Export from sheets

### ISSUE THREAD

**Issue by trevormeier** [xwiki-labs/cryptpad#478]
Currently the downloads from the "Sheets" app are .bin files, incompatible with any other tools. OnlyOffice works natively in .xlsx. It would be great to have the Sheets file downloads be .xlsx, or at least CSV files to be useful in other contexts.

**Comment by ansuz** [comment]
We've introduced support for an XLSX export as of [v3.10.0](https://github.com/xwiki-labs/cryptpad/releases/tag/3.10.0). Unfortunately it only works within Chrome or its variants, since it uses some web standards that have not been implemented in all the other browsers. Firefox-nightly supports the required functionality and apparently plans to release the update to the wider public on February 11th, 2020.
