### ISSUE TITLE
feature request: history of visited pads not stored in drive

### ISSUE THREAD

**Issue by surli** [xwiki-labs/cryptpad#482]
AFAIU the drive currently shows the history of **stored** pads that have been recently visited. However the message on the top does not specify that it shows only stored pads:
![Capture d’écran_2020-01-02_10-03-21](https://user-images.githubusercontent.com/1478232/71659245-27177c80-2d47-11ea-8a76-12db98814dad.png)

So in my case I use to visit lots of pads that I don't want to systematically put in my own drive, however I'd like to have a clear history of the pads I visited (not only mine).

**Comment by ansuz** [comment]
We're unlikely to implement a list of pads you've visited (but not stored). We offer the choice to store because implicitly storing everything represents a privacy risk as pointed out in [this issue](https://github.com/xwiki-labs/cryptpad/issues/270).

Lots of new users have raised the issue that there are too many elements grabbing your attention when you first open a document (store or not, hide the userlist, prompt to support the project...), and choosing to remember but not store a document is yet another thing to think about.

I definitely agree that the text is misleading, though. I believe we wrote that string before you had the choice not to store visited pads. We'll change that to reflect the current situation.

**Comment by surli** [comment]
> We're unlikely to implement a list of pads you've visited (but not stored). We offer the choice to store because implicitly storing everything represents a privacy risk as pointed out in this issue.

interesting, I wouldn't have imagined this kind of behaviour :) 

> Lots of new users have raised the issue that there are too many elements grabbing your attention when you first open a document (store or not, hide the userlist, prompt to support the project...), and choosing to remember but not store a document is yet another thing to think about.

Yeah definitely against adding another stuff poping up when you open a pad for that. 
Now maybe, that could be a user profile option to opt-in, to save in an history the list of all cryptpad visited. Then it would be responsibility of users to ensure #270 won't happen. 

> I definitely agree that the text is misleading, though. I believe we wrote that string before you had the choice not to store visited pads. We'll change that to reflect the current situation.

thanks for that already :+1:

**Comment by ansuz** [comment]
Fixed as of [v3.14.0](https://github.com/xwiki-labs/cryptpad/releases/3.14.0).
