### ISSUE TITLE
I think I've got the same problem. I've got a cryptpad sheet that when opened while not logged in shows the message: Editing this spreadsheet is disabled for anonymous users until it is upgraded to the latest version by a registered user. And a gray area instead of content.  When logged in it shows just the gray area instead of content.  Also the Javascript console shows lot's of 404 errors and a few of those: Access to XMLHttpRequest at 'https://files.cryptpad.fr/blob/....' from origin 'https://sandbox.cryptpad.info' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by metanoia20** [xwiki-labs/cryptpad#505]
HI.
There is no way to log in. The system constantly hashes the password and nothing happens.

**Comment by ansuz** [comment]
Our server has been having some issues over the last few days. We've tracked the problem back to the file descriptor limit set by systemd (which was launching the server). It should be resolved now.

**Comment by ansuz** [comment]
Can you confirm whether it's working now?

**Comment by ansuz** [comment]
As per [this tweet](https://twitter.com/cryptpad/status/1239997144259534853) there is a list of heuristics for identifying third-party resources that many ad-blockers use. A recent update caused many users to be unable to access CryptPad because of one line of code that mistakenly identified one of our security features as a malicious ad or tracker. Updating or disabling your adblocker should fix the problem.
