### ISSUE TITLE
Sheet .xlsx Export doesn't work / takes forever

### ISSUE THREAD

**Issue by wi18b088** [xwiki-labs/cryptpad#515]
**Describe the bug**
Export of larger sheets is not possible. I click on the export button, it gives me two options: .bin and .xlsx, .bin works within seconds, .xlxs shows spinning circle, never completes.

**Where did it happen?**
CryptPad.fr instance, logged in to my account, sheets interface

**To Reproduce**
1. Go to a sheet of larger size (3 sheets, a few formulas)
2. Click on export
3. Pick .xlsl
4. Wait forever

**Expected behavior**
I would love to download my sheets as Excel files

**Screenshots**
![image](https://user-images.githubusercontent.com/56392660/77329005-a781c400-6d1d-11ea-8877-871701bf247e.png)

**Browser (please complete the following information):**
 - OS: Linux
 - Browser: Firefox Nightly
 - Version 76.0a1
 - Extensions installed: UBlock Origin
 - Browser tweaks: none

EDIT: Tried Vanilla Chromium 80.0.3987.149 and Firefox Nightly Android as well without success.

**Additional Information**
I tried exporting smaller Sheets, they work about 50% of the time, the more sheets and formulas, the less likely that the download eventually shows up. .bin export works every time.

**Comment by ansuz** [comment]
Thanks for the report. It's possible there is an error in the middle of the export which is preventing it from terminating, or that the use of certain features just makes it _very very slow_. We'll investigate and see what we can do.

**Comment by wi18b088** [comment]
Dear ansuz,
thank you for your explanation and your quick reply.
I tried different browsers without success.
Thanks for investigating! 
Best regards

**Comment by ThisIsMissEm** [comment]
I've experienced this issue too! It very frequently gives an Out Of Memory warning for me, though, oddly, when I went to try and get the error stacktrace for here, it suddenly worked.

**Comment by ldubost** [comment]
I have had a debug session with a person having this issue on a small configuration.
He had the following error in the console:

x2t.js?ver=3.16.2:1700 Cannot enlarge memory arrays to size 155996160 bytes (OOM). Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 149880832, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 
x2t.js?ver=3.16.2:1701 Cannot enlarge memory arrays to size 155996160 bytes (OOM). Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 149880832, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 

I've pushed a fix in the OnlyOffice core wasm branch (on my repository) to replace the TOTAL_MEMORY parameter which is indeed set to 149880832 with ALLOW_MEMORY_GROWTH=1  which should allow to use more memory to be able to run the export.

Here is the fix
https://github.com/ldubost/core/commit/2f388f2c698325b2a4d9d4b9843ae8bc93dc1272

We need a rebuild of OnlyOffice wasm x2t module with this change

**Comment by ansuz** [comment]
The fix for this has been merged into today's [v3.18.1 release](https://github.com/xwiki-labs/cryptpad/releases/tag/3.18.1).
