### ISSUE TITLE
Selecting a header style does not change text formatting

### ISSUE THREAD

**Issue by jonasdagefoerde** [xwiki-labs/cryptpad#526]
**Describe the bug**
When starting a new Pad, I enter some text with default formatting. When I choose a Heading style, the heading will change its format to a larger font size (as expected). If I change the text size to another size and then select a heading style, the text is not enlarged to the proper size.

I tried to fix the formatting issue by selecting normal style and the again heading style, but to no avail.

**Where did it happen?**
The issue occured on CryptPad.fr

**To Reproduce**
1. Start a new Pad
2. Type some text and several paragraphs
3. Select the text of a one-line paragraph and set the font size to 14
3. Click into the same one-line paragraph and select the Heading 1 text style
4. The text size will not be enlarged

**Expected behavior**
The text size should be much bigger.

**Browser (please complete the following information):**
 - OS: MacOS 10.15.4
 - FF 75.0
 - FF Extensions: Enpass, Evernote, Google Analytics Opt-Out

**Comment by ansuz** [comment]
From what I can tell this is CKEditor 4's intended behaviour. If you look at [their demo](https://ckeditor.com/ckeditor-4/demo/#document) you should be able to reproduce the same behaviour where font size takes precedence over heading type.

![Screenshot from 2020-04-16 14-52-23](https://user-images.githubusercontent.com/1264398/79494996-ef7cc980-7ff1-11ea-83e7-0927a27a1553.png)

Notably, their demo provides the ability to unset font size entirely so that it will fall back to the default heading style in your use-case. There are configuration options for that, but they're not the default. I never noticed it before but I agree it's weird not to have it.

**Comment by ansuz** [comment]
[this commit](https://github.com/xwiki-labs/cryptpad/commit/c39adb9bff586f1ac9c88779ae4ea60316532ffe) implements the same thing as the CKEditor demo, but I'm not sure how to manage translations in this context. We'll investigate further and try to get a patch into the upcoming release which is planned for April 21st.

**Comment by jonasdagefoerde** [comment]
Unsetting the font formatting to get the heading style formatting would help a lot. The CKEditor 4 demo looks good: just select "default" and all your styles are gone - except the predefined one.

**Comment by ansuz** [comment]
![Screenshot from 2020-04-21 12-55-50](https://user-images.githubusercontent.com/1264398/79891770-75708a00-83cf-11ea-9fb8-98df7e01bcc3.png)

This fix is live on CryptPad.fr and included in our [3.16.0](https://github.com/xwiki-labs/cryptpad/releases/tag/3.16.0) release. For now the value isn't translated. We plan to upgrade to a newer CKEditor version in an upcoming release, which will enable this behaviour as a native function instead of as an untranslated configuration parameter.
