### ISSUE TITLE
Too many threads

### ISSUE THREAD

**Issue by pintman** [xwiki-labs/cryptpad#529]
**Describe the bug**
When starting the node server a lot (too many?) of threads are started.

**Where did it happen?**
The process on my VPS got killed.

**To Reproduce**
node server. Nothing special.

**Expected behavior**
It would be great to be able to configure the maximum number of threads that are started.

**Comment by ansuz** [comment]
Can you give the output of `lscpu` on your server? I'm looking into putting a configurable limit on the number of processes and it would be helpful to know more about the architectures we need to consider.

**Comment by pintman** [comment]
Thanks for the configurable limit. Hope the following output helps.

```
$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                20
On-line CPU(s) list:   0-19
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             20
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 61
Model name:            Intel Core Processor (Broadwell)
Stepping:              2
CPU MHz:               2199.996
BogoMIPS:              4399.99
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
NUMA node0 CPU(s):     0-19
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt
```

**Comment by luto** [comment]
@ansuz this issue originated on [uberspace.de](https://uberspace.de) where we limit users to 300 processes. So the architectures / `lscpu` is probably irrelevant in this particular case. For different but related reasons, we'll up this limit to 1024 in a future uberspace-release, though.

Nevertheless, a configurable limit would be greatly appreciated and also seems useful to other cryptpad users running it in more confined environments (e.g. small servers, embedded boards, BSD jails, stricter container setups, ...).

**Comment by ansuz** [comment]
We started using more processes because on our instance we were getting close to using the full capacity of one core. The easy fix was to launch one child process per core. The code for this wasn't really mature yet when we needed to parallelize some more tasks, so we repeated the process and used another child process per core available. For us that meant a total of 9 processes, whereas for the architecture above it would seem to mean 41.

I believe `lscpu` is equivalent to the check we use in the node process, but just to be sure you can run `node -p "os.cpus().length"`. I'd be a bit surprised if 40 child processes would be too much for the OS to handle, but maybe I'm not taking into account threads used for disk I/O.

In any case, I've already merged the two types of child processes, so the total number of processes is `N+1` instead of `2N+1` (N being the number of cores). With that in place it's now much easier to add a configurable limit.

There'll be a fix merged to our master branch for our next release (3.16.0) which we expect to have available for April 21st.

**Comment by pintman** [comment]
$ node -p "os.cpus().length"
    20

When starting ``node server`` I see the number of threads in htop increasing from 14 to 344 and the number of tasks from 11 to 52.

Thanks for your effort so far. :)

**Comment by ansuz** [comment]
I've found that child processes in nodejs are a little weird compared to other languages. They can outlive their parent for a brief amount of time, so you might see some odd numbers when restarting the server.

We've also implemented some fault recovery where new workers are spawned if an old one crashes, so it could be that workers are failing but not getting cleaned up. Whatever the case, the fact that you're seeing more than `2N+1` suggests there's some incorrect logic somewhere.

[This commit](https://github.com/xwiki-labs/cryptpad/commit/ba6faca02e7a3a8b953e1377f810da6e1a302c14#diff-a499f719c85a7caf2cf0c97cf13f026eR92-R98) implements a configurable limit for the number of workers. It's on our staging branch and tied up with some other pending updates that still need some more testing before being deployed to a production environment. I'll be interested to hear how your server handles things after `3.16.0`.

**Comment by pintman** [comment]
OK, I'll wait until version 3.16.0 is released and will report about the new beahviour.

**Comment by ansuz** [comment]
Version [3.16.0](https://github.com/xwiki-labs/cryptpad/releases/tag/3.16.0) includes support for a `maxWorkers` parameter in `config.js`. 1-2 is probably sufficient unless your server has more than 500 concurrent users.

**Comment by pintman** [comment]
Seems to be working fine. Thanks. :)
