### ISSUE TITLE
Document password shared with contacts added to document.

### ISSUE THREAD

**Issue by jakimfett** [xwiki-labs/cryptpad#530]
**Describe the bug**
When sharing a password-protected document with a contact, the contact is able to view the doc password in cleartext.

**Where did it happen?**
Via CryptPad.fr, thanks.

**To Reproduce**
1. Go to CryptDrive
2. Create a password protected document.
3. Share document with a contact.
4. Contact sees password input page, with the (obscured, but easily retrievable) cleartext password in the only visible field.

**Expected behavior**
Sharing with contacts EITHER:
requires the contact to also know the password
OR
directly sends the contact to the document, without showing them the password

**Screenshots**

**Browser (please complete the following information):**
 - OS: Linux, Debian-flavoured.
 - Browser Firefox 75.0 (Stable)
 - Extensions installed, browser tweaks: n/a
 - Version: whatever cryptpad.fr is running right now.

**Additional context**
Have some overall concerns about the threat model here...one of which is I can't seem to find your threat model, CryptPad team.

**Comment by ansuz** [comment]
![Screenshot from 2020-04-16 11-27-38](https://user-images.githubusercontent.com/1264398/79490876-8c883400-7feb-11ea-87c7-edd079b1fd15.png)

The sharing UI in the screenshot above provides a warning about this exact behaviour and links to [this section of the faq](https://cryptpad.fr/faq.html#security-pad_password).

If you share a password-protected pad via the link generator (over email or some other medium) then you will need to provide them with the password in order for them to access the document. When they enter the password it will be stored in their drive. It's in plaintext for the user, but only because they've decrypted it since everything sent to the server is encrypted.

As indicated in the FAQ, passwords are intended to protect while in transit over insecure mediums. When sharing it directly with a contact you have CryptPad as a secure channel, so we consider it safer to send the password and the document's other credentials (encryption keys and any other relevant data) all at once. We could _not_ send it to them, but we figure anyone sharing a document with another user wants them to see it.

The blue warning in the attached screenshot is not dismissable and will be shown every time you share a password-protected pad with a contact. We discussed making it yellow or some other more visible color, but decided to go with blue because we want to avoid [alert fatigue](https://en.wikipedia.org/wiki/Alarm_fatigue).

We're always open to new perspectives, but I personally think the current behaviour makes sense and matches most of our users' expectations quite well.

**Comment by ansuz** [comment]
Since there hasn't been any response I'll assume the answer above is satisfactory and close this issue.
