### ISSUE TITLE
admin/#stats shows “[object Object]” instead of Number of open files

### ISSUE THREAD

**Issue by MacLemon** [xwiki-labs/cryptpad#533]
**Describe the bug**
When visiting `admin/#stats` on our Instance, we don't get a number for open files but `[object Object]` instead.

**Where did it happen?**
https://pads.c3w.at/admin/#stats

**To Reproduce**
1. Go to https://pads.c3w.at/admin/#stats
2. See error

**Expected behavior**
Should show the number of open files.

**Screenshots**
![pads c3w at number of open files](https://user-images.githubusercontent.com/90635/79758249-72b55c80-831d-11ea-9ec5-5623f1715f86.jpg)

**Browser (please complete the following information):**
 - OS: any
 - Browser: any
   - variations: any
 - Version: any
 - Extensions installed: none
 - Browser tweaks: none

**Additional context**
- OS: Server is running FreeBSD 12.1-RELEASE-p3 (up to date as of this writing)
- node: v13.12.0
- Cryptpad 3.15.0

This is not a regression, has been that way since the number of open files was added to the stats. Hadn't taken the time to report. I consider this a minor issue.

**Comment by ansuz** [comment]
That block is generated [here](https://github.com/xwiki-labs/cryptpad/commit/f644c24362efcb39e6d65d00a08761662054c7a7#diff-24bb1db14307b003663619797fc6c7f8R10-R16). I can achieve the same result by stubbing that function with `return void cb(new Error('oops'));`, so I guess any error is just rendered as `[object Object]`.

I implemented this quickly in order to diagnose a file descriptor leak that was causing problems for CryptPad.fr. `/proc/` should be present on any linux machine (as far as I know), but apparently BSDs handle things differently.

A few possible solutions:

1. detect the OS and use the appropriate method to find the number of file descriptors opened by the current process
2. try the current method and fall back to something else if it fails
3. use a library that handles different OS-specific behaviour (I like this one the least because it increases our attack surface)

**Comment by MacLemon** [comment]
Yes, `procfs` is not available by default on FreeBSD/HardenedBSD. But it can be mounted, depending on your privileges on the host or in a jail. We run everything separated by jails.
I'll give that a try and report back if that makes a change.
