### ISSUE TITLE
Doc changes fail without warning when disk full

### ISSUE THREAD

**Issue by cyphunk** [xwiki-labs/cryptpad#553]
**Describe the bug**
I was a bit confused as over the past few days changes I would make to code documents, and now even rich text documents, would disappear at some point. Today I discovered that my instance had no more free disk space. This ideally would be a condition handled more clearly somehow. (Such as placing a warning somewhere)

**Where did it happen?**
My own instance with latest version 3.17.1. Running inside of a docker image

**To Reproduce**
How to reproduce is not clear.

**Comment by ansuz** [comment]
Hi,

We're aware of this issue but we've had limited time to address it. Until we have the chance to do so my best advice is to set up some monitoring on your server to warn before the disk becomes full.

**Comment by MacLemon** [comment]
I've recently encountered the same problem.

I'd like to suggest that CryptPad instantly puts all Pads into read-only mode when it encounters that there's no space left on device to save changes.

**Comment by ansuz** [comment]
Our upcoming 4.2.0 release includes a change where messages are neither acknowledged nor broadcast until they have been correctly stored on disk. I believe this should address this issue, however, we haven't tested to see whether write failures due to full disks are correctly handled. I'm happy to leave this issue open until somebody tests this exact case and confirms that clients react appropriately.

**Comment by ansuz** [comment]
I'm reviewing old issues and I changed my mind about leaving this open. If anyone manages to reproduce the original issue please re-open.
