### ISSUE TITLE
Rich Text not working on Firefox, works in Chrome

### ISSUE THREAD

**Issue by pludi** [xwiki-labs/cryptpad#564]
# Issue
When creating a rich text document, in Firefox it's not possible to change the formatting of the text in any way. When opening the same document in Chrome at the same time every editing option works as intended.

# Trace
In Firefox I see a these errors in the JS console, repeated at least 3 times:
```
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). common.js:2:319
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). 2 utils.js:35:9
```
These errors do *not* appear in Chrome.

# Setup
-   CryptPad: 3.16.0
-   nginx: 1.16.1 (CryptPad host)
    
    Configuration based on the 3.18.1 example configuration.
-   nginx: 1.14.0 (external TLS terminator)
-   Firefox: 77.0.1 on Ubuntu 20.04
-   Chrome: 83.0.4103.97 on Ubuntu 20.04

**Comment by kapfenho** [comment]
This also happens in Safari.

- Cryptpad: 3.18.1
- Safari: 13.1.1
- Firefox: 77.0.1

**Comment by ansuz** [comment]
Hi,

This is due to incorrectly configured Content-Security Policy (CSP) headers. This typically results from a mismatch between the two domains configured in the node server's [config.js](https://github.com/xwiki-labs/cryptpad/blob/master/config/config.example.js#L22-L67) and the corresponding nginx variables found [here](https://github.com/xwiki-labs/cryptpad/blob/master/docs/example.nginx.conf#L10-L18).

Since this isn't an issue with the product I'm going to close this issue. If the comments in those files are insufficient to get your instance working I'd advise that you ask another admin for help in our matrix channel.

**Comment by kapfenho** [comment]
Well, the problem disappeared after upgrading from 3.18.1 to 3.19.0 - without any CryptPad/nginx config change, but there might have been other upgrades in the ecosystem (or the universe - who knows?).

And a big thank you for this great app!

**Comment by ansuz** [comment]
We eliminated the use of a second set of CSP rules for the rich text editor. Those same rules are still in effect for spreadsheets, so I expect they're still broken on your instance. This is usually due to [httpSafeOrigin](https://github.com/xwiki-labs/cryptpad/blob/main/config/config.example.js#L51-L67) not being set correctly.

**Comment by kapfenho** [comment]
I don't see an issue with our sheets app (beside the open issue #569 that we experience too).

Nginx config and cryptpad config are set according the included config templates.

I've checked the browser consoles now with Firefox, Safari and Brave (Chromium):
- all report an HTTP 404 for '/common/onlyoffice/v2a/plugins.json'

Only Firefox is complaining about an inline CSP violation in a help file and that one seems weird to me:

Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). 22 ProgramInterface.htm
https://pad-sandbox.noyb.eu/common/onlyoffice/v2a/web-apps/apps/spreadsheeteditor/main/resources/help/en/ProgramInterface/ProgramInterface.htm
