### ISSUE TITLE
fresh install fails

### ISSUE THREAD

**Issue by linhux** [xwiki-labs/cryptpad#575]
CentOS7

Hi, i try to install cryptpad on my own server, after i have cloned the repos make i 
# cd cyptpad
# npm install
and now i have this error:

2347 verbose stack Error: exited with error code: 128
2347 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/pacote/lib/util/finished.js:12:19)
2347 verbose stack     at ChildProcess.emit (events.js:198:13)
2347 verbose stack     at maybeClose (internal/child_process.js:982:16)
2347 verbose stack     at Socket.stream.socket.on (internal/child_process.js:389:11)
2347 verbose stack     at Socket.emit (events.js:198:13)
2347 verbose stack     at Pipe._handle.close (net.js:607:12)
2348 verbose cwd /home/cryptpad/cryptpad
2349 verbose Linux 3.10.0-1127.13.1.el7.x86_64
2350 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
2351 verbose node v10.21.0
2352 verbose npm  v6.14.4
2353 error Error while executing:
2353 error /usr/bin/git ls-remote -h -t git://github.com/dchest/tweetnacl-js.git
2353 error
2353 error fatal: unable to connect to github.com:
2353 error github.com[0: 140.82.118.3]: errno=Connection refused
2353 error
2353 error
2353 error exited with error code: 128
2354 verbose exit [ 1, true ]

**Comment by ansuz** [comment]
It looks like a network issue. For some reason npm isn't able to reach github's servers. This is most likely an intermittent issue, so maybe try again and hopefully whatever network problem was there before should have resolved. In any case, I don't think there's anything we can do to help since the problem is unrelated to the software itself.
