### ISSUE TITLE
Console Error and Opencollective PopUP

### ISSUE THREAD

**Issue by Vibhigupta** [xwiki-labs/cryptpad#584]
There is one error in console always, and its a bit slow dont know why, for a moment it remain blank then Show up the page.

Second issue is with Opencollective Pop i make it true in config.js but it sill shows up for user.

![Cryptpad issue](https://user-images.githubusercontent.com/51713176/88476005-72e37a80-cf52-11ea-9416-407b06f17eb6.png)

**Comment by Vibhigupta** [comment]
![Cryptapad Opencollective](https://user-images.githubusercontent.com/51713176/88476167-ff426d00-cf53-11ea-9044-cd9063046e01.png)

**Comment by Vibhigupta** [comment]
@ansuz 
This is a Bug , can you help regarding this?

**Comment by ansuz** [comment]
Regarding the console.error: I can't reproduce on your instance, so I think it may be a client issue.

As for the popup, can you please share your config? Is it possible you didn't restart your server to load the new config into memory?

**Comment by ansuz** [comment]
I looked into it and apparently the opencollective popup is not configured via `config.js` but by `cryptpad/customize/application_config.js`. [It was mentioned in the release notes at the time](https://github.com/xwiki-labs/cryptpad/blame/main/CHANGELOG.md#L1343-L1344) but is otherwise undocumented. We're working on a configuration guide and I've made a note to include it there.

> Second issue is with Opencollective Pop i make it true in config.js but it sill shows up for user.

In the future, could please be more specific in your issues (preferably by following the provided issue template)? I can guess at what you mean by _i make it true_, but it makes it more difficult and time-consuming to answer.

**Comment by Vibhigupta** [comment]
Sure i will be more specific with the issue next time
