### ISSUE TITLE
Nginx Config for sandbox Domain 

### ISSUE THREAD

**Issue by Vibhigupta** [xwiki-labs/cryptpad#585]
As my sandbox throw ssl error that make sense so what config should  i use for sandbox domain.

**Comment by ansuz** [comment]
https://github.com/xwiki-labs/cryptpad/blob/main/docs/example.nginx.conf#L10-L20

**Comment by Vibhigupta** [comment]
There are Two domain

One is main and Second is sandbox so my sandbox domain is inaccessible because SSL is not configured in nginx file and neither does example nginx config contain anything related to it.

sandcrypt.inditoot.com @ansuz

**Comment by ansuz** [comment]
I'd recommend using letsencrypt to issue a single certificate for the two domains. Your nginx config would then load the one certificate and related files, and serve both domains.

In any case, we consider SSL configuration outside the scope of our software. As indicated in the example nginx config we do offer support contracts for assistance with configuration and maintenance. Otherwise, community members in our matrix channel can most likely provide some help getting your instance set up.
