### ISSUE TITLE
OnlyOffice concerns

### ISSUE THREAD

**Issue by pierreozoux** [xwiki-labs/cryptpad#586]
Hi,

As a Free Software enthusiast, I like to research solutions for daily problems.

One of this problem is for regular people be able to edit their office document within their browser in a collaborative environment.

Currently, there are 2 solutions that I'm aware of (if you know more, don't hesitate to mention them).
 - libreoffice online
 - onlyOffice

From my understanding, onlyoffice has a better technical architecture (the tiles from libreofficeonline is just a turn off for me).
But onlyOffice is backed only by one company that is starting some [shady](https://www.reddit.com/r/selfhosted/comments/fpurk6/stop_recommending_onlyoffice/) moves, and as a company, I think it will happen again.

I think the best way to resolve this would be to fork onlyOffice code into the document foundation. I know it is a long shot, but it is the only way to ensure that what the community invests there would still belong to the community.

As cryptpad is based on onlyOffice, I'd be really curious to have your insight on this matter.

Thanks for your comment, feel free to close when you want, I used it as an open forum, also, you can let me know if there is a more appropriate place for this kind of discussion.

**Comment by ansuz** [comment]
If we were going to form a foundation to ensure the long term sustainability of a software project I think we'd probably do so for CryptPad before we did it for OnlyOffice (which is only a small part of our platform).

That said, we do have an interest in ensuring that the code is maintained, but at this point I think there are enough platforms with aligned goals that I'm not personally worried about it falling into further disrepair.

**Comment by fkohrt** [comment]
> if you know more, don't hesitate to mention them

@pierreozoux Technically there's OX Documents ([code](https://gitlab.open-xchange.com/documents), [licenses](https://www.open-xchange.com/licenses-for-ox-documents/)), but their frontend UI is released under the non-commercial CC BY-NC-SA 2.5 license. Some relevant thoughts on this can be found at the [WikiSuite's list of alternatives](https://wikisuite.org/Alternatives).

I do share your concerns, especially because LibreOffice Online/Collabora CODE doesn't process documents in the browser, "there is a single, central instance of LibreOfficeKit rendering and providing document tiles to all clients" ([source](https://people.gnome.org/~michael/blog/2015-03-25-libreoffice-icewarp.html)).

**Comment by pierreozoux** [comment]
> I do share your concerns, especially because LibreOffice Online/Collabora CODE doesn't process documents in the browser, "there is a single, central instance of LibreOfficeKit rendering and providing document tiles to all clients" (source).

Yeah :) I became aware of this when I tried to investigate the code in the browser, I was hoorified ;)

**Comment by fkohrt** [comment]
@pierreozoux This might be of interest: [LibreOffice P2P](https://nlnet.nl/project/LibreOfficeP2P/)

**Comment by ansuz** [comment]
That would have been of more interest if it had existed 4 years ago when we started investing time into making OnlyOffice support encryption.

**Comment by fkohrt** [comment]
I guess so. For now I'm already happy if the projects are aware of each other and stay in contact (could not find any means of contact, though).

**Comment by ansuz** [comment]
I'm glad they're working on the problem and that NLnet is funding their project. There would just be many challenges involved in migrating away from OnlyOffice. It isn't clear whether their use of encryption would match the existing access rights systems that are used throughout CryptPad which we've applied directly to OnlyOffice. If you do find contact information feel free to inform them of our project.

**Comment by fkohrt** [comment]
> If you do find contact information feel free to inform them of our project.

They are aware of CryptPad and according to [their FOSDEM 2021 talk](https://fosdem.org/2021/schedule/event/lo_wasm/) they want to "get a demo End2End encrypted editing session going by autumn 2021".

**Comment by kolAflash** [comment]
@ansuz  
Since the beginning of the war in the Ukraine an additional concert about OnlyOffice has come up.

https://dms-solutions.co/blog/dms-solutions-stops-doing-business-with-onlyoffice-due-to-onlyoffice-close-ties-with-russia/

&nbsp;

Looks like _"Ascensio System SIA"_ (the company behind OnlyOffice) actively disguised that they are based in Russia.  
This does not necessarily make the OnlyOffice source code bad.  
But I like to ask some questions about the usage of OnlyOffice in Cryptpad.

1. To what percentage do you trust the OnlyOffice source code?
2. Have you read a lot of it and would you say, that it probably doesn't contain bad stuff like backdoors?
3. Do you maintain a fork of the OnlyOffice code, or are you simply pulling from upstream? _(regarding the above I'd see some positive arguments for a real fork)_

**Comment by ansuz** [comment]
@kolAflash I'm no longer a member of the CryptPad team, so you'll need to consult with one of the core devs.
