### ISSUE TITLE
absolute resource URLs preventing proxy_pass from subdirectory

### ISSUE THREAD

**Issue by morganrallen** [xwiki-labs/cryptpad#589]
**Describe the bug**
I'm attempting to run cryptpad in a subdirectory of an internal nginx server, `http://local-server/pad/`
The `proxy_pass` setup is working as expected but the page itself fails because it's loading resources outside it's own directory.

**Where did it happen?**
The initial HTML content loads as expected but all subsequent requests fail with `404` as they're being requested with `/` instead of `/pad/` due to being prefixed with `/`

**To Reproduce**
Replicate standard `proxy_pass` setup, with location being a subdirectory.

**Expected behavior**
HTML resources should never be prefixed with `/`, this will always force them to run in a root path.

**Comment by ansuz** [comment]
Hi,

I'm gonna be forthcoming here and let you know that I personally have a negative reaction to any issue which suggests that we're doing something which _"should never"_ be done. It implies you have a better understanding of our platform's design and assumptions than we do, and that's quite simply not the case.

That said, I understand where you're coming from, and all other things being equal I'd agree that software should be unopinionated and tolerate a variety of configurations. Your suggestion to facilitate hosting CryptPad in a subdirectory doesn't take into consideration that the use of an exclusive domain for the service is a deliberate part of our security model which takes advantage of browsers' [same-origin policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy), which restricts how scripts interact with resources from another origin.

We've designed CryptPad such that sensitive cryptographic content (login tokens, signing and encryption keys) are handled in the context of one domain, while the majority of the platform's UI code is loaded in an iframe hosted on another domain. This makes it such that in the event of an XSS vulnerability in the UI, an attacker still won't be able to access and exfiltrate your account's data. If you were to host CryptPad in a subdomain of another site (a wordpress blog, for instance) that site could interact with sensitive content from your users' accounts with the same level of access as the privileged outer domain. If the co-hosted service happened to load any scripts from a CDN, the operators of the CDN could theoretically gain complete access to all your user's accounts.

In a perfect world we'd document these assumptions and recommendations in great detail, make CryptPad capable of running in a greater variety of configurations, and let admins make informed decisions for themselves. I won't say that an admin _should never_ host CryptPad in such a manner because they could have carefully audited the co-hosted service and have a complete understanding of the security model and its implications. Since this world isn't perfect, I'm quite happy with leaving CryptPad unable to run in such a configuration as this makes it just a little bit more difficult for admins to do the wrong thing and put their users at unnecessary risk.
