### ISSUE TITLE
Add LaTeX syntax higlighting to code editor

### ISSUE THREAD

**Issue by michaelachmann** [xwiki-labs/cryptpad#59]
The code editor offers already plenty of options for code highlighting, LaTeX is however not amongst them.

**Comment by ansuz** [comment]
It seems like it's listed under [stex](https://github.com/codemirror/CodeMirror/tree/master/mode/stex). I don't know my way around LaTeX, so I can't say how well it works.

[This issue comment](https://github.com/codemirror/CodeMirror/issues/2928#issuecomment-63956053) seems to indicate that there are some difficulties with highlighting because of the complexity of the language, but an incomplete mode is probably better than a lack of one.

**Comment by michaelachmann** [comment]
Thank you for your answer! I wasn't aware that CodeMirror is being used for the code highlighting. Your link to the discussion seems to be a sufficient answer, at least for me. With a quick test the highlighting is working alright (at least with uncomplex code).

**Comment by ansuz** [comment]
Since you're satisfied I'm going to go ahead and close this.
