### ISSUE TITLE
ux: new document button is hidden in drive in recent pads

### ISSUE THREAD

**Issue by surli** [xwiki-labs/cryptpad#592]
**Describe the bug**
The "new" button that allows to create new document is quite hidden in cryptpad drive. There's 2 different bugs IMO:
  1. the "real" bug is that when looking on "Recent pads", the "new document" button is just missing. See: 
![Capture d’écran_2020-08-04_12-49-29](https://user-images.githubusercontent.com/1478232/89285870-71e8d200-d651-11ea-8cd0-855f343d7e5f.png)

  2. the "UX" bug, is that when on another page than "Recent pads" the "new document" is displayed but it's quite hard to find IMO. 
![Capture d’écran_2020-08-04_12-50-02](https://user-images.githubusercontent.com/1478232/89285879-76ad8600-d651-11ea-8dff-1f5b825167d6.png)

Personally I used to come back to the cryptpad homepage from the drive just to create a new document which is not really handy.

**Where did it happen?**
Happened on cryptpad.fr

**To Reproduce**
Just open the drive and go to "Recent pads".

**Expected behavior**
I expect to have a clear and visible menu to create a new document from the drive. Most likely in another color.

**Comment by davidbenque** [comment]
1. The `+ New` button in the drive toolbar creates a new pad at the current location. We do not show the button on the Recent Pads tab because it is not a drive location. 

2. There are multiple ways to create a new pad: 
-  From anywhere on CryptPad: `Ctrl+e`.
-  From the CryptDrive:
   - "+ NEW" in the toolbar.
   - "+ NEW" at the bottom of the file list/grid
-  From a document: **File** > **New**.

I will update our [documentation page](https://docs.cryptpad.fr/en/user_guide/apps/general.html#new-document) about this as I left out a couple of options. In any case, plenty of choices to avoid going back to the home-page to create a new pad : )

**Comment by surli** [comment]
> The + New button in the drive toolbar creates a new pad at the current location. We do not show the button on the Recent Pads tab because it is not a drive location.

Thanks for the info wasn't aware of that, but IMO the UX issue still remain since it's not obvious as a user. 

> "+ NEW" at the bottom of the file list/grid

Never noticed it since I never scroll down. Why not putting it first? 

> From anywhere on CryptPad: Ctrl+e

Cool! I'd really like to have a "+" button always displayed that would display this UI actually. It's working from "recent pads" so not sure why you couldn't display the "+ New" button and display that one there.
