### ISSUE TITLE
Heavy freeze while opening and editing documents

### ISSUE THREAD

**Issue by glu8716** [xwiki-labs/cryptpad#610]
I'm not an advanced user. I'm just using the public instance of CryptPad (at https://cryptpad.fr/) as a replace for Google Docs.
I copy-pasted from there to a CryptPad's rich text file a long document with a lot of images in it. At that moment, the document on CryptPad was fine. I then deleted the images I had on Google, reuploaded to CryptPad and readded all of them to the document.
That's when I've started to notice a heavy freeze whenever I'd open the document. I can't literally edit it now. No matter if I have to add, highlight, delete a text or change a color, as soon as I click with the mouse on the document the page freezes heavily (not only the document page, but also every page related to CryptPad, like https://cryptpad.fr/drive/).
This happens on both Firefox and Chrome, so I don't think it's a browser problem.

**Comment by ansuz** [comment]
The images in the pad should have been individually converted into encrypted files instead of the base64-encoded images which are typically used when pasting images into a document. If this conversion didn't happen for some reason then that would explain why your document is heavier than normal.

Otherwise, much of CryptPad's logic is run in your browser so that we end up only seeing encrypted content. This means that in practice performance can be limited by your device's hardware.

Because there are so many possible causes for the symptom you're seeing it's hard to comment further without seeing the actual document that's exhibiting the issue. If you're willing to share it with us via the encrypted support ticket functionality on CryptPad.fr we can investigate further.

**Comment by liu3631** [comment]
Thank you. How do I open a ticket on the site?

**Comment by ansuz** [comment]
Via [cryptpad.fr/support/](https://cryptpad.fr/support/) while logged in.

**Comment by ansuz** [comment]
I received the document you sent via support ticket. The freeze you describe seems to be a performance issue in the diffing library that we use to compare versions of the document before and after modifications to create the patches that are encrypted and sent to other users.

You can compare the speed of opening the document in edit mode vs view mode and see the difference. In edit mode the user list is encoded as a part of the document, so the diff function is triggered for the purpose of inserting your data into the user list's structure. The issue is exacerbated by the fact that you pasted foreign content into the editor, the structure of which is not as compact as content produced by the editor itself.

I do have some ideas for optimizations to make the diff function more performant on very large documents, but I'm not sure when we'll have a chance to work on them as we already have a significant backlog due to unexpected infra and support issues stemming from the pandemic. In the meantime the best I can do is suggest that you break large documents into chapters and edit them separately.

**Comment by mthld** [comment]
I successfully pasted more than 150 images into a single Rich Text document and it worked. I maybe have a powerful computer but it went fine appart taking some minutes and ruining my CryptDrive root directory. 😄

Some improvements must have been made along the way, I believe this issue can be considered as fixed.
