### ISSUE TITLE
Cryptpad install - bower issue

### ISSUE THREAD

**Issue by Toniozzzz** [xwiki-labs/cryptpad#612]
Hi,

I follow the instructions to install Cryptpad (on a Raspberry Pi with ArchlinuxARM) but when i try to create a user, the web page loading without results. In the Firefox console, i have this message :

`Require.js threw a Script Error. This probably means you're missing a dependency for CryptPad.
It is recommended that the admin of this server runs `bower install && bower update` to get the latest code, then modify their cache version.
Best of luck,
The CryptPad Developers`

So i ran 'bower install && bower update' but it's still the same thing. There is a dependency problem with  bootstrap-tokenfield#0.12.1 because it's depend on jquery#2.1.0 and Cryptpad depends on jquery#2.2.4. 
Otherwise, 'modify their cache version' means bower clean cache ?

I looked over the different issues and apologize if this issue has been already handled.

Regards,
Antoine

**Comment by ansuz** [comment]
The CryptPad server distributes a string indicating the current version of the code via the `/api/config` URL. Clients load this string and then load all subsequent resources with that value appended. This ensures that the client uses the most recent version of a file instead of an older version in their cache.

Unless you've customized your server in a radical way you should be able to update this string by restarting your server or (when your instance is already working correctly) using the `flush cache` button on the admin panel to update the string without requiring a restart.

Otherwise, @sisco0's suggestions are valid. It could be that you have an old version of node or bower. It might be helpful to review the network tab of your browser to see exactly which of the required files are failing to load.

**Comment by Toniozzzz** [comment]
Thanks a lot for both messages !
I had a problem with the node version. Here are the last versions : 

`bower : v1.8.8
node : v14.12.0
npm : v6.14.8`

In the log, i have the same result as @sisco0.
After restarting my server, checking all of environment variables and rights on files, i was able to create my user.

Just a question, when update bower, i had this warning : 

> `npm` WARN deprecated bower@1.8.8: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/ + bower@1.8.8` 

What does it mean for Cryptpad ?

Regards,
Antoine

**Comment by sisco0** [comment]
It means that _Bower_ is not intended for new projects. _Yarn_ should be used instead, these are two different package managers. _NPM_ is another package manager (**N**ode **P**ackage **M**anager).
Project should be updated to use _Yarn_ or _NPM_ in a future release.
