### ISSUE TITLE
Spreadsheets: Regional Settings not honored.

### ISSUE THREAD

**Issue by hirnidrin** [xwiki-labs/cryptpad#627]
**Describe the bug**

- In a spreadsheet, File > Advanced Settings > Regional Settings defaults to the UI language of the browser. 
- When I change the setting for the open sheet to another language/region, formatting in the sheet behaves accordingly, ok.
- When I close the (saved) sheet, then reopen it -> Regional Settings shows the default again, lost my custom setting. The sheet formats have changed back to the "unwanted" default formattings.

**Where did it happen?**
On CryptPad.fr, paid account.

**To Reproduce**
See above.

**Expected behavior**
I expect the regional setting be stored with the document, and applied on opening the document, irrelevant of browser language settings.

**Browser (please complete the following information):**
 - OS: Win 10 Pro
 - Browser: Iridium (Chromium based)
 - Version: latest
 - Extensions installed: uBlock Origin, Tracking Token Stripper
 - Browser tweaks: not aware of

**Comment by ansuz** [comment]
As of our [4.2.0 release](https://github.com/xwiki-labs/cryptpad/releases/4.2.0) spreadsheet UI will inherit language settings from the viewer's CryptPad account.

**Comment by Djfe** [comment]
Sorry for necroing this issue:
But before I open a new issue about this:
Wouldn't it make more sense those settings stay either attached to the document and are chosen depending on the document creator's settings? (because it's data and calculations are formated this way)
The viewer's cryptpad account that I shared my document with might have entirely differen regional settings.

Or is my case a special case because my data isn't stored as numbers but as text?
I have a textfield containing data like `2.94MiB`, `1.61TiB` or `8.42GiB` and convert them within the document to numbers using:
```
=WENNFEHLER(WERT(LINKS(C2,FINDEN("TiB",C2)-1)*1024),WENNFEHLER(WERT(LINKS(C2,FINDEN("KiB",C2)-1)/(1024*1024)),WENNFEHLER(WERT(LINKS(C2,FINDEN("MiB",C2)-1)/1024),WERT(LINKS(C2,FINDEN("GiB",C2)-1)))))
```
those functions are named like the following in English in the order of appearance:
IFERROR; VALUE; LEFT; FIND

The idea was taken from here:
https://www.reddit.com/r/excel/comments/qewrge/using_the_divide_formula_between_cells_that_also/
