### ISSUE TITLE
The pad does not load if the tab is not active

### ISSUE THREAD

**Issue by B0pol** [xwiki-labs/cryptpad#628]
**Describe the bug**
The pad does not load if the tab is not active (i.e. the tab loading a pad is in background)
**Where did it happen?**
Did the issue occur on CryptPad.fr or an instance hosted by a third-party?  
If on another instance, please provide its full URL.
Any cryptpad instances
**To Reproduce**
1. Open a new pad, switch tab while it loads so that the tab is in background
2. Wait few seconds.
3. Switch back to the tab loading the pad

**Expected behavior**

The pad should have been loaded in background in step 2, and visible in step 3.

**Actual behaviour**
It does not load in background, it must be an active tab to load

**Screenshots**

**Browser (please complete the following information):**
 - OS: Linux, Android
 - Browser: Firefox, ungoogled-chromium
   - variations: nightly and release
 - Version 82, 84 (firefox) - 85 (ungoogled-chromium)
 - Extensions installed some extensions, no extensions
 - Browser tweaks tweaked, not tweaked

(I send multiple info meaning I tested in these different environments)

**Comment by ansuz** [comment]
This is because Firefox and other modern browsers throttle the activitiy of asynchronous code run in the context of inactive tabs. CryptPad uses lots of asynchronous code, since we need to allow users to continue to interact with their documents while we perform relatively heavy cryptographic operations.

There isn't much we can do about this issue, so I'm going to close it. You might be interested to know that Firefox lets you configure this behaviour. To improve background loading, you can do the opposite of what is recommended in [this answer](https://superuser.com/questions/1500289/how-to-aggressively-throttle-background-tabs-in-firefox-using-dom-min-background).
