### ISSUE TITLE
Pad is missing misteriously

### ISSUE THREAD

**Issue by helenazelic** [xwiki-labs/cryptpad#635]
I edited a document in a pad that was inside a shared folder on a Cryptpad Team. After one day, with no reason, the document is missing and the link that should open it says "This link was copied from the browser's address bar and does not provide access to the document. Please use the  Share menu to share directly with contacts or copy the link. Read more about the Safe Links feature."

Why did it happened? Please, is there some way to recover the document?

**Comment by ansuz** [comment]
"Safe links" include only a document's id while its encryption keys are stored in a personal or team drive. The message you're seeing is expected under a variety of circumstances, such as if the document was removed from the shared folder by any other member of the team or if a password was added or changed.

Since this most likely concerns a particular document (presumably on CryptPad.fr) and not the open-source CryptPad software, could you please create a support ticket?
