### ISSUE TITLE
My whole cryptpad drive disappeared

### ISSUE THREAD

**Issue by everythingwaserased** [xwiki-labs/cryptpad#666]
I didn't delete it. None of my documents exist anymore. Can they be restored?

**Describe the bug**

**Where did it happen?**
Did the issue occur on CryptPad.fr or an instance hosted by a third-party?  
If on another instance, please provide its full URL.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser (please complete the following information):**
 - Browser [e.g. firefox, tor browser, chrome, safari, brave, edge, ???]
   - variations [e.g. Firefox nightly, Firefox ESR, Chromium, Ungoogled chrome]
 - Extensions installed (UBlock Origin, Passbolt, LibreJS]
 - Browser tweaks [e.g. firefox "Enhanced Tracking Protection" strict/custom mode, tor browser "safer" security level, chrome incognito mode]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by everythingwaserased** [comment]
Also, the history won't load :(

**Comment by ansuz** [comment]
Hi,

My apologies if I'm confusing you with someone else, but it seems like you submitted the same report via email as well as our Matrix channel. We tried to follow up but didn't receive any replies.

I suggested trying to log into the same account via a private browser window to identify whether the issue was related to a problem with your account or that particular session. We recently deployed some features that use browsers' storage to decrease  page loading times, so it's possible there was an invalid value stored in your local cache.

If you can confirm the results of this simple test and actually fill in the information requested via the issue template we'd be happy to investigate furtther. Otherwise I'll close this issue in some time.

**Comment by everythingwaserased** [comment]
Thank you, it was settled two days after. Best

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ansuz** [comment]
Thanks for letting us know.
