### ISSUE TITLE
How to migrate a cryptpad instance to another

### ISSUE THREAD

**Issue by romjeans** [xwiki-labs/cryptpad#669]
Hi,
I'm trying to transfer my cryptpad own instance to another server.
Making a basic copy-paste operation of the "cryptpad" directory doesn't work, I'm not able to log in using my credentials on the new server.
Could someone indicate me how to proceed ?
Thanks !
Rom

**Comment by ansuz** [comment]
Hi,

It's hard to give a definitive answer without knowing more about the configuration on your old and new machine. The `cryptpad` directory normally contains all the user data that would need to be migrated, so that should usually be enough.

It could be that the new server has different user permissions and is unable to serve files even though they're in the right place. It could also be that your node process is set up correctly but you have an incorrectly configured reverse proxy in place (like NGINX) that isn't serving files correctly.

I suggest that you:

1. try to register a new account
2. log out
3. try to log back in with the same username and password

If you're not able to log into a newly created account it's probably a deeper configuration issue and not a matter of incorrectly copied data.

**Comment by ansuz** [comment]
In any case, while we do plan to provide documentatation about how to migrate an instance, I suspect this isn't a problem with the software itself. You could try joining our community Matrix channel where other admins might be able to point you in the right direction.

I'll label this as a documentation issue so we don't forget to cover it.

**Comment by romjeans** [comment]
Hi @ansuz ,
Thanks for your replies. I re-uploaded the whole "cryptpad" directory, restarted the service and I'm able now to log in again with my old credentials on the new server. Actually I reinstalled a VPS (that was stuck) with the same exact configuration.
Thanks a lot !
Rom

**Comment by ansuz** [comment]
Thanks for the update @romjeans. For future reference, there is some information about migration in the [admin guide section of our docs](https://docs.cryptpad.fr/en/admin_guide/maintenance.html#backup-and-migration).
