### ISSUE TITLE
Nginx still duplicating headers and causing issues in Chromium browser

### ISSUE THREAD

**Issue by mark4409** [xwiki-labs/cryptpad#694]
After updating to the latest code via git pull origin main, and after restarting the cryptpad service, I'm still having issues with duplicated headers. I'm using the latest nginx example as my template. I have checked my server.js file to verify that the latest changes are there at line 110.

I am using Chromium 88.0.4324.182, and the server is on Nginx 1.19.7 and Ubuntu 20.04.2 LTS

The headers that are being duplicated are:
cache-control
Cross-Origin-Embedder-Policy
Cross-Origin-Resource-Policy

I tried restarting nginx and clearing all browser caches to no avail.

I can resolve by adding the appropriate proxy_hide_header directives in the /api/config location block

![resposes](https://user-images.githubusercontent.com/38611328/110205636-0ed24e80-7e71-11eb-8d2a-0d1d0a7ebe31.jpg)

**Comment by MacLemon** [comment]
Same here, since updating 4.2.0 (C) we still see either a bunch of duplicate headers, or when we stop sending them from `nginx` we have missing headers as there seem to be differences between `/` and for example `/code`.
We're following the `nginx.example.conf` to the letter and have also checked that our `config.js` is up-to-date and correct.

The problems seem to affect Chromium *and* Firefox based browsers now.

- Chromium 88.0.4324.96 (Official Build) (x86_64)
- Firefox 86.0
- `nginx 1.19.6_4`
- FreeBSD 12.2-RELEASE-p4
- Instance: https://pads.c3w.at/

**Comment by jbhanks** [comment]
I am having this problem again as well (works fine in Firefox but Chrome for Linux has issues with Cross-Origin-Resource-Policy).
