### ISSUE TITLE
Drive isn't loading - nginx.conf Cross-Origin-Embedder-Policy

### ISSUE THREAD

**Issue by dev4223** [xwiki-labs/cryptpad#707]
**Describe the bug**
In Chrome after login in I'll get a white screen. Dev console tells me:

https://cryptpad.hokr.us/api/config?ver=4.2.1-1616428377275 GET blocked:NotSameOriginAfterDefaultedToSameOriginByCoep

**Where did it happen?**
Self-hosted Cryptpad 4.2.1 https://cryptpad.hokr.us

**Browser (please complete the following information):**
 - OS: openSuSE LEap 15.2
 - Browser: Chrome 89.0.4389.90 (official build) (64-Bit)
 - Extensions installed: UBlock Origin, Privacy Badger, AdBlock
 - normal mode and incognito mode

**Additional context**
In Firefox it's working and if I comment out this line in my nginx.conf its working, too.

```add_header Cross-Origin-Embedder-Policy require-corp;```

**Comment by privatus** [comment]
I have the same problem with cryptpad v4.3.1.
In Firefox it's OK, but in chrome and other browsers forked from chrome after click on app or after login get blank screen.

**Comment by ansuz** [comment]
I recommend updating to the latest version (4.4.0) after reading the instructions listed in [the changelog](https://github.com/xwiki-labs/cryptpad/blob/main/CHANGELOG.md#440) since your last update.

4.4.0 includes improvements to the /changelog/ page which we've introduced over the last few releases. It will attempt to automatically diagnose your instance for commonly misconfigured values and recommend how to start debugging. Visit `http(s)://<your-instance-URL>/checkup/` to get started.
