### ISSUE TITLE
Sheet no longer working on iPad

### ISSUE THREAD

**Issue by alfkoehn** [xwiki-labs/cryptpad#709]
**Describe the bug**
Existing or new **Sheet** can no longer be opened on iPad, an error page stating **CryptPad 404** appears.

**Where did it happen?**
It occured on CryptPad.fr, using Chrome or Safari

**To Reproduce**
1. Using an iPad, go to cryptpad.fr 
2. Click on Sheet
3. See error

**Expected behavior**
A new or existing Sheet should open

**Screenshots**

**Browser (please complete the following information):**
 - OS:  iPadOS 14.4
 - Browser: Safari, Chrome

**Smartphone (please complete the following information):**
 - Device: iPad 6
 - OS:  iPadOS 14.4.
 - Browser Safari, Chrome

**Comment by ansuz** [comment]
Thanks for bringing this to our attention! We deployed an advance version of our 4.3.0 release yesterday which included a new build of OnlyOffice. I've just deployed a patch to CryptPad.fr which prevents it from trying to load a non-existent mobile version of the sheet editor.

Can you confirm that it's working correctly on your iPad?

**Comment by alfkoehn** [comment]
Thank you for fixing that so fast: yes, I can confirm that this works now on my iPad.

We have lost 2 sheets though, not sure if that was a related bug or something different: it happened when clicking on the "do you want to update" (or something similar, can't remember the exact wording) button; in most cases the new version appeared, on a few cases it didn't stop loading with the result that all the content crashed, a grey page appeared with only the header, no column or rows of the sheet (couldn't figure out any systematic, therefore no bug report).

**Comment by ansuz** [comment]
> We have lost 2 sheets though, not sure if that was a related bug or something different

We couldn't find any obvious errors in the migration code itself, so it's likely that this is from an error in OnlyOffice. Could you please share the view or edit link to one or both of these sheets via a support ticket on CryptPad.fr? We can probably patch it very quickly if we can find the root cause.

**Comment by alfkoehn** [comment]
Thank you, just submitted that support ticket!

**Comment by ansuz** [comment]
We received the ticket and manually applied some fixes to the affected sheets, so you should find that they work as expected once more. The migration should have failed entirely when the editor failed to load rather than proceeding to create a broken migration patch. We're looking into why this happened and adding some guards to automatically recover from this state for any other iPad users that were affected.

**Comment by alfkoehn** [comment]
Awesome! Documents are back, thank you very much! :+1:
