### ISSUE TITLE
sheet not opening, all other modules are working

### ISSUE THREAD

**Issue by anantmk** [xwiki-labs/cryptpad#714]
**Describe the bug**
Sheet is not opening, all other modules like Rich Text or Code are working fine.

Firefox: 

> EvalError: call to eval() blocked by CSP

Chrome: 

> Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' resource: cpad.avemunde.net".

**Where did it happen?**
selfhosted, cpad.avemunde.net

**To Reproduce**
just try to open a new sheet, happens when logged in as well as if you are not logged in

**Expected behavior**
sheet should open

**Screenshots**

![cpad_firefox](https://user-images.githubusercontent.com/19150567/114403781-60bf7000-9ba5-11eb-9d6f-8168503249a5.PNG)

![cpad_firefox_extended](https://user-images.githubusercontent.com/19150567/114404218-c9a6e800-9ba5-11eb-982b-5f4e89b405ce.PNG)

![cpad_chrome](https://user-images.githubusercontent.com/19150567/114403909-7e8cd500-9ba5-11eb-8388-a3597b32b948.PNG)

![cpad_chrome_extended](https://user-images.githubusercontent.com/19150567/114404709-41751280-9ba6-11eb-84ef-852c0a03fdad.PNG)

**Browser (please complete the following information):**
 - OS: Windows 10
 - Browsers: Firefox, Chrome
 
**Additional context**

**Comment by ansuz** [comment]
Hi,

This instance (yours, I assume) is not configured correctly.

I diagnosed the issues by visiting https://cpad.avemunde.net/checkup/, an automated instance diagnostic page we've been developing over the last few releases. Its error messages are not especially descriptive yet, but it does say that the `Main domain is not available`. This is because you've configured `"httpUnsafeOrigin"` as `"https://10.42.20.205"` in your `config.js`. Instead, it should be `"https://cpad.avemunde.net"`.

There are other configuration issues, such as the lack of sandboxing configuration (`httpSafeOrigin`). The intended usage of these parameters are described in comments in [config.js](https://github.com/xwiki-labs/cryptpad/blob/main/config/config.example.js#L22-L75).

**Comment by lcia-projects** [comment]
i'm having the same issue. unfortunately in the setup i have, i dont have a domain name assigned to it. i just need to be able to access it via the IP address (this is for a temp project) is there any work around allowing me to use sheets without a proper DNS name ?
