### ISSUE TITLE
[feature request] Link as *.url file in CryptDrive

### ISSUE THREAD

**Issue by dkuep** [xwiki-labs/cryptpad#732]
Add file-type .url/.link/.webloc as a simple link pointing to external websites or services such as Pads or Gdoc to easily integrate these in team workflows. 
This already is a feature present in Dropbox and we heavily rely on this to organise work spread out across different online services.

**Comment by cyphunk** [comment]
+1 on this. I've tried using cryptpad as a primary document source but there are times where I have to use an external service due to someone else not having fully switched or a need for a feature not available on cryptpad. It would help me keep my mental center/world within cryptpad if I could create links to those external documents somehow

**Comment by ansuz** [comment]
This feature was included in our 4.9.0 release.
