### ISSUE TITLE
[question] Pulling a pads content in an automated way (Code / Markdown)

### ISSUE THREAD

**Issue by blauertee** [xwiki-labs/cryptpad#734]
Hey,

I was wondering weather it is possible to get a static direct link to the .md file generated by the Code / Markdown Editor? 
If not I think that could be easy to implement and would make me happy. 

Thank's in advance,

Jakob

**Comment by ansuz** [comment]
Hi,

if I understand your question correctly I think you might misunderstand how CryptPad works. There isn't actually a _.md file_ that's stored on the server when you participate in an editing session. Instead, the server stores a series of encrypted changes to a document model.

Viewers load the most recent changes, decrypt them, and reconsitute those changes into the most recent state of the document. It isn't possible to download a generated version of this from the server because the server doesn't have the encryption keys required to reconstruct the document. As such, it will never be possible to do something like `wget https://cryptpad.fr/code/<stuff>.md` or to download a rendered md file in the browser without running the javascript required to decrypt and display content.

We've done a bit of work on creating command line APIs recently that will enable command-line interaction with documents, but they're still very experimental.

**Comment by blauertee** [comment]
Yes, thanks for clarifying! 
Are you saying with the API it it would be possible to pull the encrypted file content (or the history of changes that constitute the content) and then do the decryption locally? I just need an easy way to get to a files content in an automated way that is able to run on a raspberrypi.

**Comment by ansuz** [comment]
> Are you saying the API supplies an accessible routine that pulls the encrypted file content (or the history of changes that constitute the content) and does the decryption locally?

Yes. We've literally ported parts of the web client to run in nodejs.

**Comment by blauertee** [comment]
Okay, that sounds great. Where can I find find a documentation for that API or the nodejs library etc?

**Comment by jnnkB** [comment]
I think [cryptpad-tools](https://github.com/xwiki-labs/cryptpad-tools) is what you are looking for.
