### ISSUE TITLE
[4.7.0] Get Support Mailbox Public Key after generating keys from Administration interface

### ISSUE THREAD

**Issue by Asharas** [xwiki-labs/cryptpad#761]
Hi!  

After generating the Support Mailbox keys from the Administration UI there's a button to display de Private Key but is there a way to get the public key for safekeeping?

**Comment by ansuz** [comment]
In the case of [the cipher we use to encrypt support tickets](https://github.com/dchest/tweetnacl-js#naclboxkeypairfromsecretkeysecretkey) the public key can be trivially derived from the private key (but not the other way around). As such it's possible to recover from the loss of the public key.

The way the current system works is that the first authorized admin to visit this panel and use the button generates a keypair, stores the private component in their encrypted drive, and sends the public component to the server so that it can both store it in the decree log (which is used to persist server-wide preferences) and distribute it to users that want to submit support tickets (via the `/api/config` endpoint) .

There is an edge case in which the administrator destroys or fails to migrate the decree log but not the encrypted support tickets. It should be possible to recover from this if you set the `supportMailbox` manually through the instance's `config.js` (see [this line](https://github.com/xwiki-labs/cryptpad/blob/addc50b641c1fd971663e400f1b365c0915e2908/lib/env.js#L55)), however, that case should be sufficiently uncommon that adding UI to handle it will only confuse the majority of admins.

**Comment by ansuz** [comment]
To explicitly answer your question: you should see a `supportMailbox` attribute listed on your instance's `/api/config`, so you can copy it from there until dedicated UI for handling such cases is implemented.

**Comment by Asharas** [comment]
Found it, thanks :)
