### ISSUE TITLE
History feature?

### ISSUE THREAD

**Issue by nilovna** [xwiki-labs/cryptpad#78]
Hello, thanks for the great project 👍 

Is it possible to have an history feature? (It does not seem to have one).

Not sure what happened, but when a second user entered the pad using a mobile device, all the text was lost.
Having a history feature would have provided a way to go back to a previous version, instead of losing all our text.

Thanks a lot!

**Comment by ansuz** [comment]
Hi!

I'm sorry the content of your pad was lost. Given CryptPad's nature, and the difficulty of recovering content that we can't read, these are the kind of bugs we try the hardest to catch before deploying.

In order to implement a history feature, we'd need an additional API on the server for requesting a range of messages, a way to roll back through patches (in a read-only manner), and a UI that exposes that to the user in a sensible fashion. Generally the UI is the more difficult part to get right.

We're still a very small team, so though this kind of advanced feature might come in the future, it's going to be a while before we can get to it.

In the meantime, if you know what kind of mobile device was used, that might make it easier for us to figure out what went wrong to keep it from happening again.

If the document contained any critical information that you need to recover, and if you don't mind sharing the hash with us, we may be able to dump its full history into a raw format. We're on irc (and Matrix) via `#cryptpad` on Freenode.

**Comment by ansuz** [comment]
This feature was deployed to our production server (https://cryptpad.fr) this morning. It's available in our pad, code, and slide editors as a button on the right (next to import/export).
