### ISSUE TITLE
Feature Request: Chat

### ISSUE THREAD

**Issue by ventolinmono** [xwiki-labs/cryptpad#79]
First of all: Great Work!
I wonder if its in your roadmap adding chat like other etherpad services.
Cool

**Comment by ansuz** [comment]
Thanks for the compliment! I'm glad you're enjoying our service.

Just to be clear, we don't actually have any code in common with etherpad, so unfortunately it's not as simple as enabling an option. That being said, it is in our roadmap to add chat, ideally some time in the next year and a half.

Chat is usually pretty easy, but we'd like to be able to provide the same functionality in keeping with our _zero knowlege_ promise, which makes things considerably more difficult.

We're still a very small team, but hopefully with our growing user base we'll be able to justify growing our team to match.

**Comment by ventolinmono** [comment]
Yes, chat with zero knowledge would be awesome! 👍

**Comment by ansuz** [comment]
Good news: we've implemented zero knowledge chat!

It's an early prototype, and it's going to need some attention before it has an easy workflow, but you can try it out on https://cryptpad.fr right now.

Logged in users who join the same pad are able to click on a button in the userlist to add other users as contacts. Once someone has been added as a contact, you can use https://cryptpad.fr/contacts/ to open a chat session with them.

It's very basic, and only one to one chats are supported, but it's zero knowledge like the rest of CryptPad. 
Our main goal is to provide an easily integrated channel through which users can share links to new pads, so they don't have to agree on another encrypted messenger, or PGP with email, in order to share a pad.

**Comment by LeapingDragon** [comment]
Very cool project. I'd love if chat was implemented similarly to Quip:

1. A collapsible side panel with chat for the whole document
2. In-line commenting

![](https://i.imgur.com/UZmLVH1.png)

These two types of chat are very useful for _contextual collaboration_, so I don't have to go searching round for whatever the person I'm talking to is referring to.

**Comment by ansuz** [comment]
Our [contacts app](https://cryptpad.fr/contacts/) is a bit of an experiment at the moment. Once we're more confident in a the standalone chat app, we're planning to integrate it into the rest of the project.

**Comment by ansuz** [comment]
Our _master_ branch now features **contextual chat** (a chat room embedded in each pad). You can try it now on https://cryptpad.fr. The master branch will be tagged as 2.8.0 later today.
