### ISSUE TITLE
Cryptpad Forms: Answers not visible

### ISSUE THREAD

**Issue by echa2021** [xwiki-labs/cryptpad#800]
I created a password protected form (anonymus) on cryptPad.fr and the survey was answered by 30 people, but it said 0 answers when I wanted to access them in my drive. Any ideas how to get access or are the answers completely lost? Thank you!

**Comment by davidbenque** [comment]
Hello. Sorry it took us a while to reproduce this. We found an issue where the server rejected answers because the password on the form had been added/changed after the document was created and/or after the link was shared. We have now disabled password change for Forms to prevent this from happening until we can find a better solution. This will not bring your data back but it will prevent others from having similar issues.
