### ISSUE TITLE
Feature request: integrate with IFTTT / Zapier / Huginn / etc.

### ISSUE THREAD

**Issue by evolverine** [xwiki-labs/cryptpad#808]
It would open a whole new world of automation. E.g. take any number of useful actions when a user fills in a form, or when a document has been updated, a comment replied to, etc.

**Comment by ansuz** [comment]
In order to make decisions based on changes to documents the CryptPad server would need to have access to documents' encryption keys. We have no plans to provide such integrations for the mainline project, however, if you have a budget for this work we could provide consultation services to help you modify your instance.

**Comment by mthld** [comment]
Hi,

Regarding the absence of answer I'll now be closing this issue. As mentioned by my colleague, don't hesitate to contact us at sales@cryptpad.fr if you need our services.
