### ISSUE TITLE
Show notification when someone submits a form

### ISSUE THREAD

**Issue by evolverine** [xwiki-labs/cryptpad#809]
Currently, there is no way to know when a form has been submitted, except if we keep logging in and checking. That's not ideal, for most uses of the forms app. At a minimum, there could be a notification in the usual notifications panel. Ideally, one could also choose to receive emails when forms are submitted.

**Comment by mfaure** [comment]
(First and foremost, thank you very much for this great piece of software!)

To complete the described use case, to me not having an email notification is almost a stopper. Without it, I can't replace [Framadate](https://framadate.org/).

Hope this helps :)

**Comment by raldoori** [comment]
Hi there.

Were there any updates about this? I see that it's been completed but I don't know if it's been implemented already.

**Comment by ghost** [comment]
Hello @raldoori,

> Were there any updates about this? I see that it's been completed but I don't know if it's been implemented already.

It has been implemented since a long time already. For every response to a form, by default you receive a notification in the notification tray of your account.

If you are facing issues, please reach out on our [community forum](https://forum.cryptpad.org) or our [Matrix public space](https://matrix.to/#/#cryptpad:matrix.xwiki.com).
