### ISSUE TITLE
Automatic expiration & removal

### ISSUE THREAD

**Issue by loganto** [xwiki-labs/cryptpad#81]
Hi - I find this project absolutely amazing.  
Would be absolutely lovely if some automatic deletion could be added if user specifies expiration time.

**Comment by ansuz** [comment]
Thanks, I'm glad you find CryptPad useful!

We've been discussing the idea of making it possible for the creator of a pad to delete that from the server. Some code is already in place to manage parts of that process, but it will need significant work before it's ready. Since it destroys data we're going to be _very_ careful about deploying it. When that infrastructure in place, automatic expiration should be reasonably simple to implement.

Unlike the clientside code which users can audit, users will just have to trust us that we're actually deleting the data and not just putting it out of reach. You're not the first to express interest in this, and I'd say it's quite likely we'll get to it eventually, but for now we're going to try to expand the range of functionality that can be implemented in a user-verifiable fashion.

**Comment by Maikel-Predikkta** [comment]
This is exactly what I was looking for. My use case:

Share a secret with a third party that doesn't know about crypto stuff.

1. I create a pad and set the expiration time to a couple of days.
2. I store a secret there.
3. I send the link to the third party mentioning the automatic deletion.
4. They have two days to copy the secret.
5. After two days, the link in the email is useless.
6. Any attacker spying on the mailboxes has a very low chance of obtaining a secret unless they spy for a long time and actively download all content from links.

**Comment by ansuz** [comment]
We've been actively working on pad expiration, though it has yet to be deployed. Our next release will feature a _pad creation screen_ which will allow users to decide if a pad should expire, and when, ranging from 1 hour to 99 months.
