### ISSUE TITLE
Upload fails with files larger than 300MB

### ISSUE THREAD

**Issue by gabrielpreite** [xwiki-labs/cryptpad#828]
When uploading a file larger than 300MB (I tried .txt, .mkv and .mp4 files) the web page freezes and disconnects from the server after ~30 seconds. A snapshot of the page memory shows a size of 300+MB, the whole file plus the page base size.

Smaller files upload without issues, but after a failed attempt with a large one uploading stops working until i reload my page.

Upload limit is set at 1GB and max storage for my user is 200GB.

**Where did it happen?**
Happens consistently on self hosted instance of promasu/cryptpad on Unraid 6.9.2, docker version 4.12.0

**To Reproduce**
1. Open cryptdrive folder
2. Upload any file larger than 300MB
3. Enter
4. Page freezes, after ~30s two error messages appear: "Disconnected from server" and "Server Error: unable to upload your file at this time."

**Expected behavior**
File uploaded and showing in cryptdrive folder

**Screenshots**
Before attempt to upload
![Screenshot_2](https://user-images.githubusercontent.com/47240121/140897819-8af4b11c-8190-4e23-8762-fdc3652e89aa.png)
After
![Screenshot_3](https://user-images.githubusercontent.com/47240121/140897888-dfc73290-45e9-46eb-816c-1f6894400e67.png)

**Browser (please complete the following information):**
 - OS: Win10 10.0.19043
 - Browser Firefox
 - Version 94.0.1
 - Extensions installed AdBlocker Ultimate
 - Browser tweaks None

**Comment by MrCyjaneK** [comment]
#804 got the same issue.

**Comment by ansuz** [comment]
File upload as it currently exists in CryptPad was only ever intended to supplement our collaborative document editing capabilities by allowing users to embed small files (images, audio, PDFs, or reasonably sized videos). Server settings are unrelated to the failure in this instance as it seems to be the client that is freezing and throwing errors.

I'd like to be able to support this use-case, but since there are already a variety of open-source e2ee file backup/sharing solutions and our team is quite small this is unlikely to be prioritized over our primary use-cases (collaborative editing) for the foreseeable future.

**Comment by MrCyjaneK** [comment]
That makes sense. However are there any plans on adding cryptpad support to tools like rclone or providing some kind of tool to mount the cryptpad into filesystem?

**Comment by ansuz** [comment]
Perhaps in late 2022 provided we can find the funding to do so.

**Comment by DillFrescott** [comment]
My instance says `Error code: STATUS_BREAKPOINT` and does it immediately when trying to upload a file thats only ~180 MB

**Comment by mthld** [comment]
Hello,

As mentioned by my colleague @ansuz previously, it's likely due to web browser issues. See our "Common issue" section in our documentation FAQ: https://docs.cryptpad.fr/en/FAQ.html#common-issues

Please note that Unraid, Docker & AdBlocker Ultimate aren't officially supported. If you need help setting up your instance I encourage you to contact us at sales@cryptpad.fr, we'll be able to provide support.
