### ISSUE TITLE
Error when create new user

### ISSUE THREAD

**Issue by msvp** [xwiki-labs/cryptpad#833]
Hello from France !

On my own Cryptpad (V4.12.0), behind an Nginx, I've got a problem when new user search to create a new count : 
Uncaught TypeError: Cannot read properties of undefined (reading 'curvePrivate')

Any Idea ?

Thanks !

**Comment by mthld** [comment]
Hello,

Thanks for your report.

I encourage you to check out our "Common issues" section of our documentation FAQ: https://docs.cryptpad.fr/en/FAQ.html#common-issues (available in french if needed). It's likely that your issue can be triggered by an untested web browser, or an extension breaking CryptPad functionalities.

Otherwise, we do not provide configuration/setup support on GitHub, we invite you to reach us at sales@cryptpad.fr if you need help.
