### ISSUE TITLE
OnlyOffice questions

### ISSUE THREAD

**Issue by reyaz006** [xwiki-labs/cryptpad#848]
1. Sheets editor UI zoom is quite low and is not easily changed. On a usual 15-inch laptop with 125% dpi setting in Windows it feels tiny, even though crisp. It only ever zooms in when I zoom in to 200% in browser, and not earlier. It also zooms too much at this point. Is there any relevant option I'm missing?
2. Conditional formatting works but I'm not finding any possibility to set or edit it. Is it just not there?
3. Can't seem to find an option to open/edit/convert uploaded Word and RTF documents. Is it possible?
4. From what I've seen so far, only Sheets editor is used from OnlyOffice suite. Is this correct and is there a particular reason for this? E.g. Docs and Presentations could also be handled by OnlyOffice.

**Comment by ansuz** [comment]
Hi,

we integrated OnlyOffice's Doc and Presentation editors in October. On CryptPad.fr they are only available to premium users, but their code is open-source and they can be enabled on self-hosted instances. More information about them is available in [our October blog post](https://blog.cryptpad.org/2021/10/27/status-2021-10/).

I believe the rest of the issues will be fixed by an update to a more recent version of OnlyOffice which will be included in our upcoming release.

**Comment by jamesbeebop** [comment]
Just curious which version of OnlyOffice will be used in the upcoming release?  There's a v7 feature I'm specifically looking for.  :)

**Comment by mthld** [comment]
OnlyOffice upcoming work to upgrade to v7 is now being discussed on the community forum: https://forum.cryptpad.org/d/22-upgrade-onlyoffice-to-7x

I'm closing this issue in favor of this thread. :)
