### ISSUE TITLE
The bounce application must only be used from the sandbox domain

### ISSUE THREAD

**Issue by AmarOk1412** [xwiki-labs/cryptpad#855]
**Describe the bug**

+ Open a text editor
+ "Fichier"->"Aide"
It opens an empty tab with "The bounce application must only be used from the sandbox domain, please report this issue on https://github.com/xwiki-labs/cryptpad"

**Where did it happen?**
Only seen on https://ebauche.facil.services/bounce/#https%3A%2F%2Fdocs.cryptpad.fr%2Ffr%2Fuser_guide%2Fapps%2Frichtext.html (https://ebauche.facil.services ; v4.12.1)
The nginx config is similar from the docs, but even in https://github.com/xwiki-labs/cryptpad/blob/main/docs/example.nginx.conf I don't see anything related to /bounce. I don't experience this on other instances, so we may missed a config.

**Expected behavior**
It should go to the FAQ from docs.cryptpad.fr (btw why it's not hosted by the app?)

**Comment by ansuz** [comment]
It looks like you have a serverside redirect rule in place for `https://ebauche-sandbox.facil.services` which sends the client to `https://ebauche.facil.services` rather than the intended destination. The page's script halts as soon as this is detected and displays this error because it isn't meant to be run outside of the sandbox.

You can correct this by removing the incorrect redirect.
