### ISSUE TITLE
Change documents' background color?

### ISSUE THREAD

**Issue by Yolakalemowa** [xwiki-labs/cryptpad#878]
Hi, 

I tried searching the issues and I don't think I found this one. 

Is it possible to change the background color of documents to other than white? 

That would work very well with the nice dark mode. 

Thanks for a great product.

**Comment by Jakeler** [comment]
If someone is searching for the forum thread, there is one since January 2024: https://forum.cryptpad.org/d/216-dark-mode-for-rich-text-background

While a built in solution would be better I found that Dark Reader (browser extension) works well too:

![grafik](https://github.com/user-attachments/assets/8e0a5691-79a5-4646-923d-74996b0ff167)
