### ISSUE TITLE
The changed image size is restored after saving

### ISSUE THREAD

**Issue by youyuxiansen** [xwiki-labs/cryptpad#899]
**Describe the bug**
The changed image size is restored after saving

**Where did it happen?**
Just on default XWiki, not using other plugins.

**To Reproduce**
1. insert an image
2. Change the size
3. Save

**Expected behavior**

**Screenshots**

**Browser (please complete the following information):**
 - OS: MacOS 11.6.4(chrome), ubuntu20.04(firefox)
 - Version 13.10.5 (deployed with https://github.com/xwiki/xwiki-docker.git 13 docker compose)
 - Extensions installed (MathJax Macro 1.0.2, XWiki Standard Flavor 13.10.5, CommonMark Markdown Syntax 1.2 8.7.1 (in global namespace))

**Comment by ansuz** [comment]
Hi,

The XWiki and CryptPad platforms are both developed by XWiki SAS, but they are separate projects.

Issues for the XWiki platform are currently tracked on Jira. One of my colleagues advised that your issue seems related to [this one](https://jira.xwiki.org/browse/MARKDOWN-39).

Since this doesn't concern the CryptPad platform I'll close this issue.
