### ISSUE TITLE
feature request: picture upload

### ISSUE THREAD

**Issue by Espo02** [xwiki-labs/cryptpad#90]
Is it possible to upload automatically pictures and store them on the server encrypted?
Maybe automatically resized and a max size of xx.kb 
In some documents it would be really usefull.

... Just my two Cents ;)

**Comment by ansuz** [comment]
We've been talking about doing this for a while, so it's nice to hear that there's interest in it.

I've used [Up1](https://github.com/Upload/Up1) for this kind of thing, but since the assets are encrypted, we need to write some integration code. We want to be able do things like upload when dragging and dropping into CKEditor or our presentation editor.

I'm planning to write up a blog post about our road map for the next while, which will detail when we think we'll be able to deliver some of the features people keep asking for. It'll be posted to https://blog.cryptpad.fr.

Thanks for your interest!

**Comment by Espo02** [comment]
My thoughts about this are:
The Server Confing must allow to set max upload size, or max size of an document.
Maybe an "automatic deleted after x days"
Very nice would it be, if only the logged in Users can upload files and the admin could define the usernames which are allowed to upload files.
Without such restrictions the servers could ran out of space.
I'm running an instance of cryptpad under xempay.org

**Comment by ansuz** [comment]
We've implemented encrypted file upload in today's release, but it will still require significant work before it's ready to be used by the public.

Some issues:

1. we're going to change the encoding before the next release, so any files that you upload on your own CryptPad instances won't continue to work after updating. After that they should be stable.
2. we don't currently limit upload size, or otherwise limit how much any particular user can upload
