### ISSUE TITLE
Uncaught SyntaxError: Unexpected token D in JSON at position 0

### ISSUE THREAD

**Issue by mbomb007** [xwiki-labs/cryptpad#902]
**Describe the bug**

A document or sheet often fails to load on https://cryptpad.fr, giving this error.

> Uncaught SyntaxError: Unexpected token D in JSON at position 0

**Where did it happen?**
https://cryptpad.fr

**To Reproduce**
1. Open a sheet or doc. It doesn't happen every time, and while often, it is inconsistent.
2. Errors in browser console (see below)
3. Sometimes, it loads after waiting. I also have it where the sheet becomes impossible to edit. I'm not sure if it's because of this, or because of an error after pasting into cells.

```
Uncaught SyntaxError: Unexpected token D in JSON at position 0
    at JSON.parse (<anonymous>)
    at onMsg (main.js?ver=4.14.1-00:40:76)
onMsg @ main.js?ver=4.14.1-00:40
postMessage (async)
(anonymous) @ VM100 content_script.js:503

Uncaught Uncaught SyntaxError: Unexpected token D in JSON at position 0
window.onerror @ boot2.js?ver=4.14.1-00:77
```

**Expected behavior**
The doc or sheet loads reliably every time.

**Screenshots**

**Browser (please complete the following information):**
 - OS: Windows 7
 - Browser: Brave Version 1.38.109 Chromium: 101.0.4951.41 (Official Build) (64-bit)
 - Extensions installed: Adblock Plus, other stuff. It can't be the extensions, because it works sometimes.
 - Browser tweaks: N/A

**Additional context**

**Comment by katchy3132** [comment]
I am getting : 

`Uncaught SyntaxError: Unexpected token o in JSON at position 1`

in a similar setup : Chrome 101/ Windows 10.

**Comment by gnyman** [comment]
I had an almost identical error, but `Uncaught SyntaxError: Unexpected token G in JSON at position 0`, for me the rich text editor worked but not the code editor, it failed every time. Both worked fine in Incognito though (i.e. without any extensions), I tracked it down to the SuperAgent extension interfering somehow.

I'd recommend trying in an incognito window and see if it happens there, otherwise try disabling extensions one by one until you find the one which interfere.

I took a quick look at the trying to figure out what goes wrong, and it seems the issue (for me) is that it ends up here
https://github.com/xwiki-labs/cryptpad/blob/5979aafdee90aab232658374b11aca8331fd0421/www/common/outer/worker-channel.js#L171
and when SuperAgent is enabled, `data.msg` is somehow modified or changed. For me it has been changed to a string, which fails when trying to parse it as JSON.
![Brave Browser-Code - Fri 13 May 2022-20220513-164845](https://user-images.githubusercontent.com/1233346/168297874-2d268c5f-abf5-4b74-aad5-b8a1ecb13934.png)

Hopefully this helps, let me know if I can provide more info.

This is using
Brave [Version 1.38.115 Chromium: 101.0.4951.64 (Official Build) (x86_64)](https://brave.com/latest/)
on macOS 12.3.1

**Comment by ansuz** [comment]
Thanks @gnyman, that's very helpful!

@mbomb007, @katchy3132: can you confirm whether you also have the SuperAgent extension installed?

**Comment by mbomb007** [comment]
I do not have that extension.

The main extensions I use are:

Adblock Plus (I don't use this on Brave anymore, because Brave has built-in blocking.)
Canvas Fingerprint Defender
Disable HTML5 Autoplay

**Comment by katchy3132** [comment]
I dont have SuperAgent installed. But I disabled Canvas Fingerprint Defender and Font Fingerprint Defender and it seems to work

**Comment by mthld** [comment]
Hello,

Thanks for your reports, as of today there is little we can do about those extensions breaking CryptPad functionalities. I encourage you to check out our official documentation regarding this kind of issues: https://docs.cryptpad.fr/en/FAQ.html#common-issues
