### ISSUE TITLE
Translations are gone :O

### ISSUE THREAD

**Issue by pojebunny** [xwiki-labs/cryptpad#92]
The main page has been updated and with that update all the previously created translations are gone.
I can translate it back to polish (as I did the original), but you'll have to contact others to redo theirs if they want.

**Comment by ansuz** [comment]
We've made a lot of changes lately, but haven't contacted our translation contributors yet because we might not be quite done changing text.

We're planning to [release a major version every two weeks](https://blog.cryptpad.fr/2017/02/24/Announcing-biweekly-releases/), with the next release coming on the 14th of March.

We've made a page which displays missing keys (per language) [here](https://cryptpad.fr/assert/translations/). It displays the original English text beside the key, so hopefully translating will be easier than it was before. It also lists keys which are no longer present in the English translation, meaning they are no longer used.

Our release notes from our [1.1.0 release](https://github.com/xwiki-labs/cryptpad/releases/tag/1.1.0) contain some notes for translators, since some keys were changed, and not added or deleted.

Any PRs merged before the 14th will make it into our next deployment. If there's any way we can help, please let us know. As always, we're on IRC (now bridged with Matrix).

**Comment by ansuz** [comment]
ping @h3ct0rjs @ProgVal @michaelachmann @gustavohmsilva

**Comment by h3ct0rjs** [comment]
hi @ansuz  I will check the new words to translate it to spanish in this weekend, I will just need a quick overview how the translation proccess is being made. 

Regards, 
Hector F.

**Comment by ansuz** [comment]
@h3ct0rjs, @pbondoer recently started working for XWiki, and he helped us out with the Spanish translations. I'd like to know if there are any dialectic differences between Spain and South America, but it should mostly be a review.

If there are differences, we can discuss them, and maybe fork the file by regional codes.

**Comment by michaelachmann** [comment]
I have the German translation on my schedule, but can't promise any timeframe just yet since I have an important deadline ahead of me.

**Comment by ansuz** [comment]
@michaelachmann thanks! There's no rush on our end. We'll just roll it into the following release whenever it's merged.

**Comment by h3ct0rjs** [comment]
Hi @ansuz  After reviewing the spanish translation(351 lines) to me It seems ok. Good job @pbondoer :crown:. I was thinking why we're not using CI software, after making a few personal test for me seems pretty cool.

**Comment by h3ct0rjs** [comment]
@ansuz let me know when you need help or review :smile:  

Regards
