### ISSUE TITLE
Update marked lib to avoid potential XSS

### ISSUE THREAD

**Issue by Framartin** [xwiki-labs/cryptpad#97]
Slide can be vulnerable to an XSS attack **if** the CSP headers are disabled

## How to reproduce

- An attacker creates an slide containing a malicious link: `[naughty link](javascript:alert('xss'&#41;)`
- (S)he shares it with a targeted user
- The targeted user clicks on the link
- The payload is executed if CSP headers are disabled

## How to fix

Updating the marked library should [fix it](https://github.com/chjj/marked/pull/592).

**Comment by Framartin** [comment]
I think that the cause of this issue is [this other issue](https://github.com/chjj/marked/issues/815#issuecomment-284559830).

**Comment by ansuz** [comment]
Unfortunately marked.js uses the `sanitize` flag to strip all HTML, which we don't want to do since it offers users some more control over their slides' appearance.

Since we do strip out script and a variety of other tags before inserting them into the DOM, and we do apply CSP headers, this doesn't seem like a serious threat to users.

**Comment by Framartin** [comment]
If you are filtering the content, you can force links to start by `http`, or strip `href` starting by `javascript:`, `vbscript:` or `data:`.

If the CSP headers are a key to mitigate this potential XSS, I think it may be good to indicate it in the README, or somewhere else, in order for future sys-admin to be aware of that (so that they don't disable it for convenient modifications).

**Comment by cjdelisle** [comment]
My understanding is we need to check for things like `java script:` and `JaVaScRiPt:` and `&#106;&#97;&#118;&#97;....` etc. as per this: https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet

**Comment by kpcyrd** [comment]
It might make more sense to just whitelist protocols: `http`, `https`, and `ftp` are probbly the most obvious.

**Comment by rugk** [comment]
Remember that CSP is only a fallback security/protection-feature. Your application should be safe against XSS attacks (anyway).

**Comment by cjdelisle** [comment]
I'm going to close this issue because updating the marked lib will not change anything. We are not using the sanitize feature in marked because it filters innocent and sometimes necessary html such as `<style>` or `<center>`.

You will notice that if you disable CSP, you can simply insert `<script>alert('hi')</script>` into a presentation and it will be executed when the document loads. We recognize sanitizing is a fool's game and we choose instead to use sandboxing.
