### ISSUE TITLE
Repative unrecoberable error in Kanban

### ISSUE THREAD

**Issue by petrenkonikita112263** [xwiki-labs/cryptpad#978]
### Contribution guidelines

- [X] I've read the [code of conduct](https://github.com/xwiki-labs/cryptpad/blob/main/CODE_OF_CONDUCT.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I've read the [Common issues documentation section](https://docs.cryptpad.org/en/FAQ.html#common-issues) and I also checked [previous issues](https://github.com/xwiki-labs/cryptpad/issues).

### Description

The bug is reproduced, as I assume, for the guest user on Kanban notes that the registered user created.  The error will be displayed on the tab blinking in the infinity loop. Also, the document's status will blink between **Editing**->**Saved**->**Disconnected**. It's impossible to hit buttons in the error window; only reload helps.

The image of the error.
![image](https://user-images.githubusercontent.com/56109799/197475971-1e77d74e-3bda-487e-b597-b6b3127ffaf9.png)

### Steps to reproduce

1. Login into CryptPad
2. Create a default Kanban document with some sheets
3. Allow editing for any users (including guests) by providing the link to this document
4. The author has to be still logged in, and the tab with the document must be opened
5. Open in a browser as a new tab the document using provided link as a guest
6. Make some changes in the document (it'll automatically save by CryptPad)
7. Don't close the tab and don't reload it; leave it for a while (1 hour or more)
8. Switch back to it, and there will be a pop-up window with the error

### Expected behavior

No error shall be displayed for guest (visitor) users. Or there shall be an info message about the timeout session with further asking to authorize to continue or automatically reload the table

### System information

| Question | Answer |
| --- | --- |
| Operating system and version | Windows 10 Pro 21H2 |
| Web browser and version| Microsoft Edge 106.0.1370.47 and latest |
| Extensions installed | Grammarly, Passbolt |
| Browser tweaks | None |
| CryptPad version | 5.1.0 |

**Comment by mthld** [comment]
Hello,

This is likely due to some web browser incompatibility issues. Please see the ["Common Issues" section](https://docs.cryptpad.org/en/FAQ.html#common-issues) of our documentation FAQ.

If you have an issue with your document please reach out to your administrators, using [the integrated support system](https://docs.cryptpad.org/en/user_guide/user_account.html#support) so they can take a look at your file.

If you're having general issues like this, please go over [the forum](https://forum.cryptpad.org) and create a topic to describe what you are facing and receive community support.

I'll now be closing this GitHub issue, thanks.
